### ISSUE TITLE
Vector field transaction exception

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#1167]
Specific to vector, scalar works fine
```
>>> import ansys.fluent.core as pf
>>> solver = pf.launch_fluent(mode="solver")
>>> solver.transcript.stop()
>>> solver.read_case(file_name="E:/elbow.cas.h5")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\ansysdev\pyfluent17\pyfluent\src\ansys\fluent\core\session.py", line 134, in __getattr__
    return getattr(self.fluent_connection, attr)
AttributeError: '_FluentConnection' object has no attribute 'read_case'
>>> solver.file.read_case(file_name="E:/elbow.cas.h5")
'*cx-overwrite-prompt?*'
>>> solver.solution.initialization.hybrid_initialize()
>>> data_trans = solver.field_data.new_transaction()
>>> data_trans.add_vector_fields_request(field_name='velocity', surface_ids=[0])
>>> data_trans.get_fields()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\ansysdev\pyfluent17\pyfluent\src\ansys\fluent\core\services\field_data.py", line 583, in get_fields
    return extract_fields(self._service.get_fields(self._fields_request))
  File "e:\ansysdev\pyfluent17\pyfluent\src\ansys\fluent\core\services\field_data.py", line 758, in extract_fields
    for chunk in chunk_iterator:
  File "E:\ANSYSDev\pyfluent17\.env\lib\site-packages\grpc\_channel.py", line 426, in __next__
    return self._next()
  File "E:\ANSYSDev\pyfluent17\.env\lib\site-packages\grpc\_channel.py", line 826, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:10.121.3.99:50433 {grpc_message:"Stream removed", grpc_status:2, created_time:"2022-12-07T20:10:44.172910518+00:00"}"
>
```

**Comment by seanpearsonuk** [comment]
OK in 24R1
