### ISSUE TITLE
Bug located in create mesh interfaces of solution

### ISSUE THREAD

**Issue by loverchun** [ansys/pyfluent#1365]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When I want to create mesh interfaces with periodic repeats, I have write the following command:
`tui.define.mesh_interfaces.create('l', 'lgap-r', [], 'jbg-l', [], 'no', 'yes', 'no')`. 
Then I get the error. However, I can realize the correct result in Fluent TUI Command. I want to know what I did wrong.

### 📝 Steps to reproduce

[1.zip](https://github.com/pyansys/pyfluent/files/10757067/1.zip)
First of all, unzip the zip file and you can get the mesh file named 1.
Secondly, open the python and input the following code.
```
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent(
    product_version="23.1.0", precision="double", version="2d", processor_count = 6, mode="solver") 
msh_filename = "1.msh" 
solver.file.read_mesh(file_name = msh_filename)
tui = solver.tui
tui.define.boundary_conditions.fluid(
    'jbg',
    'n', 'n', 'n', 'n', 0, 'n', 0, 
    'yes',
    -1, 'n', 0, 'n', 0, 'n',
    45.553,
    'quit'
)
tui.define.mesh_interfaces.create('l', 'lgap-r', [], 'jbg-l', [], 'no', 'yes', 'no')
```
When you run the above code, you will receive the prompt as following:
```
RuntimeError: 000002258BF0F3A0ointer to Thread conversion
Error Object: #f
```

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
pip install ansys-fluent-core
```

**Comment by seanpearsonuk** [comment]
@loverchun please could you also show an equivalent direct TUI usage in Fluent that works, then we can possibly find if a different transformation is required between TUI and TUI API. For instance, if any of your TUI arguments were quoted strings, then they have to be quoted in the TUI API usage thus `some/command "some-argument"` becomes `solver.tui.some.command('"some-argument"')`.

If there is no such working Fluent version then one can potentially use the normal service request channels.

**Comment by loverchun** [comment]
您好，您的邮件我已收到，我会尽快给您回复，谢谢！

**Comment by loverchun** [comment]
> @loverchun please could you also show an equivalent direct TUI usage in Fluent that works, then we can possibly find if a different transformation is required between TUI and TUI API. For instance, if any of your TUI arguments were quoted strings, then they have to be quoted in the TUI API usage thus `some/command "some-argument"` becomes `solver.tui.some.command('"some-argument"')`.
> 
> If there is no such working Fluent version then one can potentially use the normal service request channels.

Hi seanpearsonuk, thanks for your apply. When I use Fluent TUI, I input the following command:
'''
/define/mesh-interfaces/create
'''
Then I need to write the name of mesh interface and another operation. And I'll write it down here.
'''
l lgap-r  ()  jbg-l   ()  no  yes no  
'''
I think there is not TUI arguments were quoted strings, but I don't know where I'm wrong.
Looking forward to your reply.

**Comment by seanpearsonuk** [comment]
@loverchun 

So this works through the TUI?  Please try the recrdong your commands as a Pyyhon journal. Then you can try to run that as a script in either PyFluent or the Fluent Python console. Please let us iknow the outcome.

cc; @mkundu1

**Comment by loverchun** [comment]
> @loverchun
> 
> Does this work through the TUI?
> 
> Please record your TUI commands as a Python journal. Then you can try to run that as a script in either PyFluent or the Fluent Python console. Please let us know the outcome. Thanks
> 
> cc; @mkundu1

When I use TUI in ansys 2023R2, I get the following message: 
```
Error at host: 00000183B1258EA0ointer to Thread conversion
Error Object: #f
```
But I can succeed in ansys 2020R2. I don't know why it happens.

**Comment by seanpearsonuk** [comment]
@hpohekar please could you try the direct TUI interaction with a current build of Fluent?

**Comment by hpohekar** [comment]
@seanpearsonuk Yes, sure.

**Comment by loverchun** [comment]
您好，您的邮件我已收到，我会尽快给您回复，谢谢！

**Comment by hpohekar** [comment]
We get following errors if we execute above code.

PyFluent output - 

```
>>> import ansys.fluent.core as pyfluent
>>> solver = pyfluent.launch_fluent(product_version="23.1.0", precision="double", version="2d", processor_count = 6, mode="solver", show_gui=True)
>>> solver.file.read_mesh(file_name=r"C:\Users\hpohekar\Downloads\1\1.msh")

AAPQ13pUvWxQtxN has other FLUENT parallel processes running.                       Process affinity not being set.
Reading "C:\Users\hpohekar\Downloads\1\1.msh"...
Buffering for file scan...

  324244 nodes.
       2 mixed shadow faces, zone  8.
       2 mixed periodic faces, zone  9.
       2 shadow face pairs. 
     811 mixed shadow faces, zone 10.
     811 mixed periodic faces, zone 11.
     811 shadow face pairs. 
       2 mixed shadow faces, zone 12.
       2 mixed periodic faces, zone 13.
       2 shadow face pairs. 
   32788 mixed wall faces, zone 14.
     360 mixed interface faces, zone 15.
     360 mixed interface faces, zone 16.
     393 mixed interface faces, zone 17.
     393 mixed interface faces, zone 18.
     393 mixed interface faces, zone 19.
     393 mixed interface faces, zone 20.
      75 mixed interface faces, zone 21.
      60 mixed interface faces, zone 22.
      74 mixed interface faces, zone 23.
      75 mixed pressure-outlet faces, zone 24.
      60 mixed pressure-inlet faces, zone 25.
      74 mixed pressure-inlet faces, zone 26.
  592744 mixed interior faces, zone 28.
  291960 quadrilateral cells, zone  2.
     786 quadrilateral cells, zone  3.
     786 quadrilateral cells, zone  4.
    4350 quadrilateral cells, zone  5.
    3480 quadrilateral cells, zone  6.
    4292 quadrilateral cells, zone  7.

The following option has been enabled to improve particle tracking with periodic boundaries.
  define/models/dpm/numerics/high-resolution-tracking/use-quad-face-centroid?

To overide this, the following option must first be disabled.
  define/models/dpm/numerics/high-resolution-tracking/always-use-face-centroid-with-periodics?


Building...
     mesh
        auto partitioning mesh by Metis (fast),
        distributing mesh
                pairs......,
                parts......,
      wall -> wall (14) and wall:027 (27)
      wall -> wall (14) and wall:029 (29)
      wall -> wall (14) and wall:030 (30)
      default-interior -> default-interior (28) and default-interior:031 (31)
      default-interior -> default-interior (28) and default-interior:032 (32)
      default-interior -> default-interior (28) and default-interior:033 (33)
      default-interior -> default-interior (28) and default-interior:034 (34)
      default-interior -> default-interior (28) and default-interior:035 (35)
                faces......,
Note: Separating wall zone 14 into zones 14 and 27.
Note: Separating wall zone 14 into zones 14 and 29.
Note: Separating wall zone 14 into zones 14 and 30.
Note: Separating interior zone 28 into zones 28 and 31.
Note: Separating interior zone 28 into zones 28 and 32.
Note: Separating interior zone 28 into zones 28 and 33.
Note: Separating interior zone 28 into zones 28 and 34.
Note: Separating interior zone 28 into zones 28 and 35. 
                nodes......,
                shadow nodes......,
                cells......,
        bandwidth reduction using Reverse Cuthill-McKee: 44249/59 = 749.983
     materials,
     interface,
     domains,
     zones,
        default-interior:035
        default-interior:034
        default-interior:033
        default-interior:032
        default-interior:031
        wall:030
        wall:029
        wall:027
        default-interior
        hpin
        lpin
        mpout
        hpout
        lpout
        mpin
        lgap-l
        lgap-r
        rgap-l
        rgap-r
        jbg-l
        jbg-r
        wall
        p-rgap
        p-rgap_shadow
        p-jbg
        p-jbg_shadow
        p-lgap
        p-lgap_shadow
        hp
        lp
        mp
        lgap
        rgap
        jbg
     parallel,
Done.
True
>>> solver.tui.define.boundary_conditions.fluid(
...     'jbg',
...     'n', 'n', 'n', 'n', 0, 'n', 0,
...     'yes',
...     -1, 'n', 0, 'n', 0, 'n',
...     45.553,
...     'quit'
... )
(jbg rgap lgap mp lp hp)


ERROR: Please answer y[es] or n[o].
Error object: 0





ERROR: Please answer y[es] or n[o].
Error object: -1





ERROR: Please answer y[es] or n[o].
Error object: 0





ERROR: Please answer y[es] or n[o].
Error object: 0





ERROR: Please answer y[es] or n[o].
Error object: 45.553





ERROR: Please answer y[es] or n[o].
Error object: quit




Error at host: get_time_interpolated_value: profile \\"\\" does not exist.

Error: get_time_interpolated_value: profile \\"\\" does not exist.
Error Object: ()


Error at Node 5: get_time_interpolated_value: profile \\"\\" does not exist.ErrorError at Node 5: get_time_interpolated_value: profile \\"\\" does not exist.Error
:
Error at Node 0: get_time_interpolated_value: profile \\"\\" does not exist.eval: unbound variablerror at Node 0: get_time_interpolated_value: profile \\"\\" does not exist.eval: unbound variable

Error at Node 1: get_time_interpolated_value: profile \\"\\" does not exist.ErrorError at Node 1: get_time_interpolated_value: profile \\"\\" does not exist.Error
 Object:  Object:
Error at Node 4: get_time_interpolated_value: profile \\"\\" does not exist.\\Error at Node 4: get_time_interpolated_value: profile \\"\\" does not exist.\\

Error at Node 2: get_time_interpolated_value: profile \\"\\" does not exist.

Error at Node 3: get_time_interpolated_value: profile \\"\\" does not exist.

Error: An error occurred in the previous operation.
       The details can be found in the text output.
Error Object: #f

Error: eval: unbound variable
Error Object:

Error: eval: unbound variable
Error Object: #f

Error: An error occurred in the previous operation.
       The details can be found in the text output.
Error Object: #f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Repos\pyfluent\src\ansys\fluent\core\services\datamodel_tui.py", line 328, in __call__
    return PyMenu(self._service, self._version, self._mode, self._path).execute(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repos\pyfluent\src\ansys\fluent\core\services\datamodel_tui.py", line 217, in execute
    return self._execute_command(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repos\pyfluent\src\ansys\fluent\core\services\datamodel_tui.py", line 184, in _execute_command
    ret = self._service.execute_command(request)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repos\pyfluent\src\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: An error occurred in the previous operation.
       The details can be found in the text output.
Error Object: #f
>>>
```

Fluent console output - 

```
> 
AAPQ13pUvWxQtxN has other FLUENT parallel processes running.                       Process affinity not being set.
Reading "C:\Users\hpohekar\Downloads\1\1.msh"...
Buffering for file scan...

  324244 nodes.
       2 mixed shadow faces, zone  8.
       2 mixed periodic faces, zone  9.
Warning: Reversing 2 faces, zone  9.
       2 shadow face pairs. 
     811 mixed shadow faces, zone 10.
     811 mixed periodic faces, zone 11.
Warning: Reversing 811 faces, zone 11.
     811 shadow face pairs. 
       2 mixed shadow faces, zone 12.
       2 mixed periodic faces, zone 13.
Warning: Reversing 2 faces, zone 13.
       2 shadow face pairs. 
   32788 mixed wall faces, zone 14.
Warning: Reversing 174 faces, zone 14.
     360 mixed interface faces, zone 15.
     360 mixed interface faces, zone 16.
     393 mixed interface faces, zone 17.
     393 mixed interface faces, zone 18.
     393 mixed interface faces, zone 19.
     393 mixed interface faces, zone 20.
      75 mixed interface faces, zone 21.
      60 mixed interface faces, zone 22.
      74 mixed interface faces, zone 23.
      75 mixed pressure-outlet faces, zone 24.
      60 mixed pressure-inlet faces, zone 25.
      74 mixed pressure-inlet faces, zone 26.
  592744 mixed interior faces, zone 28.
  291960 quadrilateral cells, zone  2.
     786 quadrilateral cells, zone  3.
     786 quadrilateral cells, zone  4.
    4350 quadrilateral cells, zone  5.
    3480 quadrilateral cells, zone  6.
    4292 quadrilateral cells, zone  7.

The following option has been enabled to improve particle tracking with periodic boundaries.
  define/models/dpm/numerics/high-resolution-tracking/use-quad-face-centroid?

To overide this, the following option must first be disabled.
  define/models/dpm/numerics/high-resolution-tracking/always-use-face-centroid-with-periodics?


Building...
     mesh
	auto partitioning mesh by Metis (fast),
	distributing mesh
		pairs......,
		parts......,
      wall -> wall (14) and wall:027 (27)
      wall -> wall (14) and wall:029 (29)
      wall -> wall (14) and wall:030 (30)
      default-interior -> default-interior (28) and default-interior:031 (31)
      default-interior -> default-interior (28) and default-interior:032 (32)
      default-interior -> default-interior (28) and default-interior:033 (33)
      default-interior -> default-interior (28) and default-interior:034 (34)

		faces......,
Note: Separating wall zone 14 into zones 14 and 27. 
Note: Separating wall zone 14 into zones 14 and 29. 
Note: Separating wall zone 14 into zones 14 and 30. 
Note: Separating interior zone 28 into zones 28 and 31. 
Note: Separating interior zone 28 into zones 28 and 32. 
Note: Separating interior zone 28 into zones 28 and 33. 
Note: Separating interior zone 28 into zones 28 and 34. 
Note: Separating interior zone 28 into zones 28 and 35. 
		nodes......,
		shadow nodes......,
		cells......,
        bandwidth reduction using Reverse Cuthill-McKee: 44249/59 = 749.983
     materials,
     interface,
     domains,
     zones,
	default-interior:035
	default-interior:034
	default-interior:033
	default-interior:032
	default-interior:031
	wall:030
	wall:029
	wall:027
	default-interior
	hpin
	lpin
	mpout
	hpout
	lpout
	mpin
	lgap-l
	lgap-r
	rgap-l
	rgap-r
	jbg-l
	jbg-r
	wall
	p-rgap
	p-rgap_shadow
	p-jbg
	p-jbg_shadow
	p-lgap
	p-lgap_shadow
	hp
	lp
	mp
	lgap
	rgap
	jbg
     parallel,
Done.
(jbg rgap lgap mp lp hp)


ERROR: Please answer y[es] or n[o].
Error object: 0





ERROR: Please answer y[es] or n[o].
Error object: -1





ERROR: Please answer y[es] or n[o].
Error object: 0





ERROR: Please answer y[es] or n[o].
Error object: 0





ERROR: Please answer y[es] or n[o].
Error object: 45.553





ERROR: Please answer y[es] or n[o].
Error object: quit




Error at host: get_time_interpolated_value: profile \"\" does not exist.
      default-interior -> default-interior (28) and default-interior:035 (35)
Error: get_time_interpolated_value: profile \"\" does not exist.
Error Object: ()


ErrorError at Node 5: get_time_interpolated_value: profile \"\" does not exist.
: 
eval: unbound variableError at Node 0: get_time_interpolated_value: profile \"\" does not exist.


ErrorError at Node 1: get_time_interpolated_value: profile \"\" does not exist.
 Object: 
\\Error at Node 4: get_time_interpolated_value: profile \"\" does not exist.


Error at Node 2: get_time_interpolated_value: profile \"\" does not exist.

Error at Node 3: get_time_interpolated_value: profile \"\" does not exist.

Error: An error occurred in the previous operation.
       The details can be found in the text output.
Error Object: #f

Error: eval: unbound variable
Error Object: 

Error: eval: unbound variable
Error Object: #f

Error: An error occurred in the previous operation.
       The details can be found in the text output.
Error Object: #f
 
```

**Comment by seanpearsonuk** [comment]
Thanks very much @hpohekar. There is an issue with the mesh file. This is not a saient problem for the PyFluent team to address.
