### ISSUE TITLE
Ctrl+C interrupted session.exit() causes future session.exit() calls to not do anything

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#1675]
```
>>> session.exit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\fluent_connection.py", line 521, in exit
    self._finalizer()
  File "C:\Program Files\Python310\lib\weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\fluent_connection.py", line 564, in _exit
    scheme_eval.exec(("(exit-server)",))
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\services\scheme_eval.py", line 286, in exec
    response = self.service.exec(request)
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\services\scheme_eval.py", line 54, in exec
    return self.__stub.Exec(request, metadata=self.__metadata)
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_interceptor.py", line 247, in __call__
    response, ignored_call = self._with_call(request,
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_interceptor.py", line 287, in _with_call
    call = self._interceptor.intercept_unary_unary(continuation,
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 47, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 32, in _intercept_call
    response = continuation(client_call_details, request)
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_interceptor.py", line 274, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_interceptor.py", line 301, in with_call
    return self._with_call(request,
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_interceptor.py", line 287, in _with_call
    call = self._interceptor.intercept_unary_unary(continuation,
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 125, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "E:\ansysdev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 116, in _intercept_call
    return continuation(client_call_details, request)
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_interceptor.py", line 274, in continuation
    response, call = self._thunk(new_method).with_call(
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_channel.py", line 1041, in with_call
    state, call, = self._blocking(request, timeout, metadata, credentials,
  File "E:\ansysdev\venv_default\lib\site-packages\grpc\_channel.py", line 1017, in _blocking
    event = call.next_event()
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 338, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 169, in grpc._cython.cygrpc._next_call_event
  File "src\python\grpcio\grpc\_cython\_cygrpc/channel.pyx.pxi", line 163, in grpc._cython.cygrpc._next_call_event
  File "src\python\grpcio\grpc\_cython\_cygrpc/completion_queue.pyx.pxi", line 78, in grpc._cython.cygrpc._latent_event
  File "src\python\grpcio\grpc\_cython\_cygrpc/completion_queue.pyx.pxi", line 61, in grpc._cython.cygrpc._internal_latent_event
  File "src\python\grpcio\grpc\_cython\_cygrpc/completion_queue.pyx.pxi", line 42, in grpc._cython.cygrpc._next
KeyboardInterrupt
>>> session.exit()
>>> session.exit()
>>> session.check_health()
'SERVING'
```
Logs only register a single exit gRPC call
`2023-06-08 16:42:16,593 pyfluent.networking   DEBUG    GRPC_TRACE: rpc = /grpcRemoting.SchemeEval/Exec, request = {'command': ['(exit-server)'], 'wait': True, 'silent': True}`

None of the subsequent ones seem to do anything at all, as if `session.exit()` was now redirected somewhere else other than `fluent_connection`

Is it maybe the weakref finalizer that dies after being used once, or something similar?

**Comment by raph-luc** [comment]
@hpohekar I think your ctrl+c did not interrupt anything there, looking at the logs you shared:
```
>>> solver.exit()
>>> 
KeyboardInterrupt
```

I think it should've instead looked like:
```
>>> session.exit()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
...
KeyboardInterrupt
>>>
```

Regardless, this is not a big issue, so its fine if you want to close it I think
