### ISSUE TITLE
Bug in launcher

### ISSUE THREAD

**Issue by NSchmidtRose** [ansys/pyfluent#1950]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I am trying to launch Fluent from Python while using the journal_filepath keyword, but it seems like the use of that keyword is not implemented internally. 
I will read the journal in a separate command for now.

Traceback (most recent call last):
  File "/home/srn/.conda/envs/PyFluent/lib/python3.8/site-packages/ansys/fluent/core/launcher/launcher.py", line 677, in launch_fluent
    session.file.read_journal(journal_filepath)
TypeError: __call__() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../fluent_schleife.py", line 102, in <module>
    run_fluent(kerne,f"/CFD_NAS/Ablage_Werkzeuge/Entwicklung/PyQueue/2_Laeuft/{FALL_AKTUELL}")
  File "../fluent_schleife.py", line 41, in run_fluent
    solver=pyfluent.launch_fluent(
  File "/home/srn/.conda/envs/PyFluent/lib/python3.8/site-packages/ansys/fluent/core/launcher/launcher.py", line 690, in launch_fluent
    raise LaunchFluentError(launch_string) from ex
ansys.fluent.core.launcher.launcher.LaunchFluentError: 
Fluent Launch string: /ansys_inc/v232/fluent/bin/fluent 3ddp -t36 -mpi=intel -platform=intel -nm -ssh -pshmem -sifile="/tmp/serverinfo-tb61h_ld.txt" -nm

### 📝 Steps to reproduce

solver=pyfluent.launch_fluent(
        precision="double",
        version="3d", 
        processor_count=kerne,
        mode="solver",
        show_gui=True, 
        additional_arguments="-mpi=intel -platform=intel -nm -ssh -pshmem",
        journal_filepath=journal

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

23R2

### 🐍 Which Python version are you using?

3.8

### 📦 Installed packages

```shell
aiohttp==3.8.4
aiosignal==1.3.1
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client @ file:///tmp/build/80754af9/anaconda-client_1635330891925/work
ansys-api-fluent==0.3.12
ansys-api-platform-instancemanagement==1.0.0b3
ansys-fluent-core==0.16.0
ansys-fluent-visualization==0.7.1
ansys-platform-instancemanagement==1.0.3
anyio @ file:///tmp/build/80754af9/anyio_1644481698350/work/dist
appdirs==1.4.4
argon2-cffi @ file:///opt/conda/conda-bld/argon2-cffi_1645000214183/work
argon2-cffi-bindings @ file:///tmp/build/80754af9/argon2-cffi-bindings_1644569684262/work
arrow==0.13.1
astroid @ file:///tmp/build/80754af9/astroid_1628063142195/work
async-timeout==4.0.2
atomicwrites==1.4.0
attrs @ file:///opt/conda/conda-bld/attrs_1642510447205/work
autopep8 @ file:///opt/conda/conda-bld/autopep8_1639166893812/work
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1618170165463/work
backports.tempfile @ file:///home/linux1/recipes/ci/backports.tempfile_1610991236607/work
backports.weakref==1.0.post1
beautifulsoup4 @ file:///tmp/build/80754af9/beautifulsoup4_1631874778482/work
binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work
black==19.10b0
bleach @ file:///opt/conda/conda-bld/bleach_1641577558959/work
Bottleneck==1.3.2
bqplot @ file:///home/conda/feedstock_root/build_artifacts/bqplot_1633081325276/work
brotlipy==0.7.0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cffi @ file:///opt/conda/conda-bld/cffi_1642701102775/work
chardet @ file:///tmp/build/80754af9/chardet_1607706746162/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click @ file:///tmp/build/80754af9/click_1646038465422/work
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1632508026186/work
clyent==1.2.2
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
coloredlogs==14.0
conda-content-trust @ file:///tmp/build/80754af9/conda-content-trust_1617045594566/work
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1618262148928/work
conda-repo-cli @ file:///tmp/build/80754af9/conda-repo-cli_1620168426516/work
conda-souschef @ file:///home/conda/feedstock_root/build_artifacts/conda-souschef_1661977243124/work
conda-verify==3.4.2
cookiecutter @ file:///tmp/build/80754af9/cookiecutter_1617748928239/work
cryptography @ file:///tmp/build/80754af9/cryptography_1633520369403/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
cytoolz==0.11.0
dask==2021.10.0
debugpy @ file:///tmp/build/80754af9/debugpy_1637091796427/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
diff-match-patch @ file:///Users/ktietz/demo/mc3/conda-bld/diff-match-patch_1630511840874/work
docker==6.1.3
docutils @ file:///tmp/build/80754af9/docutils_1620827984873/work
dolfyn==0.12
entrypoints==0.3
et-xmlfile==1.1.0
filelock @ file:///opt/conda/conda-bld/filelock_1642510437405/work
flake8 @ file:///tmp/build/80754af9/flake8_1620776156532/work
fonttools==4.25.0
frozenlist==1.3.3
fsspec @ file:///opt/conda/conda-bld/fsspec_1642510437511/work
future==0.18.2
glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work
googleapis-common-protos==1.58.0
grayskull @ file:///home/conda/feedstock_root/build_artifacts/grayskull_1669825743080/work
grpcio==1.51.1
h5py==3.8.0
humanfriendly==8.2
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
imagecodecs @ file:///tmp/build/80754af9/imagecodecs_1635529103369/work
imageio @ file:///tmp/build/80754af9/imageio_1617700267927/work
imagesize @ file:///tmp/build/80754af9/imagesize_1637939814114/work
img2pdf==0.4.0
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1638542885373/work
importlib-resources==5.12.0
inflection==0.5.1
intervaltree @ file:///Users/ktietz/demo/mc3/conda-bld/intervaltree_1630511889664/work
ipydatawidgets @ file:///home/conda/feedstock_root/build_artifacts/ipydatawidgets_1609929402090/work
ipykernel @ file:///opt/conda/conda-bld/ipykernel_1662361798230/work
ipylab==1.0.0
ipympl @ file:///home/conda/feedstock_root/build_artifacts/ipympl_1661165023080/work
ipython @ file:///tmp/build/80754af9/ipython_1643818147236/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipyvolume @ file:///home/conda/feedstock_root/build_artifacts/ipyvolume_1618924410810/work
ipywebrtc @ file:///home/conda/feedstock_root/build_artifacts/ipywebrtc_1617018267587/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1634143127070/work
isort @ file:///tmp/build/80754af9/isort_1628603791788/work
jedi @ file:///tmp/build/80754af9/jedi_1644315233700/work
jeepney @ file:///tmp/build/80754af9/jeepney_1627537048313/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
jinja2-time @ file:///tmp/build/80754af9/jinja2-time_1617751524098/work
jproperties==2.1.1
json5 @ file:///tmp/build/80754af9/json5_1624432770122/work
jsonschema @ file:///Users/ktietz/demo/mc3/conda-bld/jsonschema_1630511932244/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1616770841739/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1616615302928/work
jupyter-core @ file:///tmp/build/80754af9/jupyter_core_1636524756443/work
jupyter-kite==2.0.2
jupyter-server @ file:///opt/conda/conda-bld/jupyter_server_1644494914632/work
jupyterlab @ file:///opt/conda/conda-bld/jupyterlab_1647445413472/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///opt/conda/conda-bld/jupyterlab_server_1644500396812/work
jupyterlab-templates @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_templates_1616944541817/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
keyring @ file:///tmp/build/80754af9/keyring_1638531356231/work
kiwisolver @ file:///opt/conda/conda-bld/kiwisolver_1638569886207/work
lazy-object-proxy @ file:///tmp/build/80754af9/lazy-object-proxy_1616526917483/work
libarchive-c @ file:///tmp/build/80754af9/python-libarchive-c_1617780486945/work
locket==0.2.1
lxml==4.9.2
MarkupSafe==1.1.1
matplotlib @ file:///tmp/build/80754af9/matplotlib-suite_1645455682260/work
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186064646/work
mkl-service==2.4.0
multidict==6.0.4
munkres==1.1.4
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbclassic @ file:///opt/conda/conda-bld/nbclassic_1644943264176/work
nbclient @ file:///tmp/build/80754af9/nbclient_1645431659072/work
nbconvert @ file:///opt/conda/conda-bld/nbconvert_1641309195684/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx @ file:///tmp/build/80754af9/networkx_1633639043937/work
notebook @ file:///tmp/build/80754af9/notebook_1645002536250/work
numexpr @ file:///tmp/build/80754af9/numexpr_1640704208950/work
numpy==1.24.1
numpydoc @ file:///opt/conda/conda-bld/numpydoc_1643788541039/work
ocrmypdf==11.2.1
olefile @ file:///Users/ktietz/demo/mc3/conda-bld/olefile_1629805411829/work
openpyxl @ file:///tmp/build/80754af9/openpyxl_1632777717936/work
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.4.1
pandocfilters @ file:///opt/conda/conda-bld/pandocfilters_1643405455980/work
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
partd @ file:///tmp/build/80754af9/partd_1618000087440/work
pathspec==0.7.0
pdfminer.six==20200726
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
pikepdf==1.19.3
Pillow==8.4.0
pkginfo @ file:///tmp/build/80754af9/pkginfo_1643162084911/work
platformdirs==3.5.3
pluggy @ file:///tmp/build/80754af9/pluggy_1633715052817/work
pooch==1.7.0
poyo @ file:///tmp/build/80754af9/poyo_1617751526755/work
progressbar2 @ file:///home/conda/feedstock_root/build_artifacts/progressbar2_1666856063684/work
prometheus-client @ file:///opt/conda/conda-bld/prometheus_client_1643788673601/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1633440160888/work
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.5
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pycodestyle @ file:///tmp/build/80754af9/pycodestyle_1615748559966/work
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyDictH5==0.2.1
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1621600989141/work
pyflakes @ file:///tmp/build/80754af9/pyflakes_1617200973297/work
Pygments @ file:///opt/conda/conda-bld/pygments_1644249106324/work
PyJWT @ file:///tmp/build/80754af9/pyjwt_1619651636675/work
pylint @ file:///tmp/build/80754af9/pylint_1627536788098/work
pyls-spyder==0.4.0
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///tmp/build/80754af9/pyparsing_1635766073266/work
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1636110947380/work
PySide6==6.2.4
PySocks @ file:///tmp/build/80754af9/pysocks_1605305779399/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-lsp-black @ file:///tmp/build/80754af9/python-lsp-black_1634232156041/work
python-lsp-jsonrpc==1.0.0
python-lsp-server==1.2.4
python-slugify @ file:///tmp/build/80754af9/python-slugify_1620405669636/work
python-utils @ file:///home/conda/feedstock_root/build_artifacts/python-utils_1667318130351/work
pythreejs @ file:///home/conda/feedstock_root/build_artifacts/pythreejs_1614691447028/work
pytz==2021.3
pyvista==0.39.1
pyvistaqt==0.10.0
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1601658317819/work
pyxdg @ file:///tmp/build/80754af9/pyxdg_1603822279816/work
PyYAML==6.0
pyzmq @ file:///tmp/build/80754af9/pyzmq_1638436375034/work
QDarkStyle @ file:///tmp/build/80754af9/qdarkstyle_1617386714626/work
qstylizer @ file:///tmp/build/80754af9/qstylizer_1617713584600/work/dist/qstylizer-0.1.10-py2.py3-none-any.whl
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1637160816833/work
qtconsole @ file:///opt/conda/conda-bld/qtconsole_1643819126524/work
QtPy @ file:///opt/conda/conda-bld/qtpy_1643087291789/work
rapidfuzz @ file:///home/conda/feedstock_root/build_artifacts/rapidfuzz_1671613635020/work
regex @ file:///opt/conda/conda-bld/regex_1642021319040/work
reportlab==3.5.53
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
rope @ file:///opt/conda/conda-bld/rope_1643788605236/work
Rtree @ file:///tmp/build/80754af9/rtree_1618420845272/work
ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016699510/work
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1666827402316/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1670412724006/work
ruamel.yaml.jinja2==0.2.4
scikit-image==0.18.3
scipy @ file:///tmp/build/80754af9/scipy_1641555001653/work
scooby==0.7.2
SecretStorage @ file:///tmp/build/80754af9/secretstorage_1614022784285/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1632406701022/work
shiboken6==6.2.4
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1644875935023/work
sniffio @ file:///tmp/build/80754af9/sniffio_1614030475067/work
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1637937080595/work
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1623949099177/work
soupsieve @ file:///tmp/build/80754af9/soupsieve_1636706018808/work
Sphinx @ file:///opt/conda/conda-bld/sphinx_1643644169832/work
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///tmp/build/80754af9/sphinxcontrib-serializinghtml_1624451540180/work
spyder @ file:///tmp/build/80754af9/spyder_1636480225430/work
spyder-kernels @ file:///tmp/build/80754af9/spyder-kernels_1634236926649/work
stdlib-list @ file:///home/conda/feedstock_root/build_artifacts/stdlib-list_1667495268108/work
terminado @ file:///tmp/build/80754af9/terminado_1644322581811/work
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
text-unidecode @ file:///Users/ktietz/demo/mc3/conda-bld/text-unidecode_1629401354553/work
textdistance @ file:///tmp/build/80754af9/textdistance_1612461398012/work
three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work
tifffile @ file:///tmp/build/80754af9/tifffile_1627275862826/work
tinycss @ file:///tmp/build/80754af9/tinycss_1617713798712/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
tomli_w @ file:///home/conda/feedstock_root/build_artifacts/tomli-w_1638551719419/work
toolz @ file:///tmp/build/80754af9/toolz_1636545406491/work
tornado @ file:///tmp/build/80754af9/tornado_1606942300299/work
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
traitlets @ file:///tmp/build/80754af9/traitlets_1636710298902/work
traittypes @ file:///home/conda/feedstock_root/build_artifacts/traittypes_1600843364635/work
trame==2.5.0
trame-client==2.9.0
trame-components==2.1.1
trame-deckgl==2.0.2
trame-markdown==2.0.2
trame-matplotlib==2.0.2
trame-plotly==2.1.1
trame-rca==0.3.1
trame-router==2.0.2
trame-server==2.11.4
trame-simput==2.3.2
trame-vega==2.0.3
trame-vtk==2.4.4
trame-vuetify==2.2.4
typed-ast @ file:///tmp/build/80754af9/typed-ast_1624953673417/work
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
ujson @ file:///opt/conda/conda-bld/ujson_1640703856928/work
Unidecode @ file:///tmp/build/80754af9/unidecode_1614712377438/work
urllib3 @ file:///opt/conda/conda-bld/urllib3_1643638302206/work
vtk==9.2.6
watchdog @ file:///tmp/build/80754af9/watchdog_1638366565112/work
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
websocket-client @ file:///tmp/build/80754af9/websocket-client_1614804261064/work
whichcraft @ file:///tmp/build/80754af9/whichcraft_1617751293875/work
widgetsnbextension @ file:///tmp/build/80754af9/widgetsnbextension_1645009353553/work
wordcloud @ file:///home/conda/feedstock_root/build_artifacts/wordcloud_1610646778963/work
wrapt==1.12.1
wslink==1.11.0
wurlitzer @ file:///tmp/build/80754af9/wurlitzer_1638354972036/work
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
yarl==1.9.2
zipp @ file:///opt/conda/conda-bld/zipp_1641824620731/work
```

**Comment by seanpearsonuk** [comment]
@prmukherj See here: https://github.com/ansys/pyfluent/pull/1335/files. For a settings API call, named argument is needed.
