### ISSUE TITLE
Getting issue with PyFluent Workflow with monitors, report definitions

### ISSUE THREAD

**Issue by abhishekchitwar** [ansys/pyfluent#1966]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Getting following traceback while executing pyfluent workflow. 

Workflow includes monitor data 

``` 
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\host_name\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-15:
Traceback (most recent call last):
  File "C:\Users\host_name\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\Users\host_name\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
    self.run()
  File "C:\Users\host_name\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
  File "C:\Users\host_name\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self.run()
  File "C:\Users\host_name\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\events_streaming.py", line 52, in _process_streaming
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\events_streaming.py", line 52, in _process_streaming
    self._target(*self._args, **self._kwargs)
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\events_streaming.py", line 52, in _process_streaming
    call_back(
    call_back(
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 143, in refresh
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 143, in refresh
    call_back(
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 143, in refresh
    self.start()
    self.start()
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\streaming.py", line 63, in start
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\streaming.py", line 63, in start
    self.start()
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\streaming.py", line 63, in start
    self._prepare()
    self._prepare()
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 146, in _prepare
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 146, in _prepare
    self._prepare()
    self._update_dataframe()
    self._update_dataframe()
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 193, in _update_dataframe
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 193, in _update_dataframe
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 146, in _prepare
    monitors_name = list(monitor_set_info["monitors"]) + ["xvalues"]
    monitors_name = list(monitor_set_info["monitors"]) + ["xvalues"]
KeyError: 'monitors'
KeyError: 'monitors'
    self._update_dataframe()
  File "d:\Research\test\dev\.venv\lib\site-packages\ansys\fluent\core\streaming_services\monitor_streaming.py", line 193, in _update_dataframe
    monitors_name = list(monitor_set_info["monitors"]) + ["xvalues"]
KeyError: 'monitors'
```

### 📝 Steps to reproduce

Set report definitions, e.g., 
```python

solver.solution.report_definitions.volume["max-temp"] = {
	"report_type": "volume-max",
	"zone_names": ["cell_zone"],
	"field": "temperature",
}
solver.solution.monitor.report_plots["max-temp-track"] = {
	"report_defs": ["max-temp"],
}
solver.solution.monitor.report_files["max-temp-track"] = {
	"file_name": r".\\max-track-temp-over-time.out",
	"report_defs": ["max-temp"],
}
solver.solution.monitor.report_files["max-temp-track"].report_defs = [
	"max-temp",
	"flow-time",
]
solver.solution.report_definitions.single_val_expression["charge-into-track"] = {
	"define": "charge_in"
}
solver.solution.monitor.report_plots["charge-into-track"] = {}
```

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

V2023R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
ansys-api-fluent==0.3.12
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.16.0
ansys-platform-instancemanagement==1.1.2
asttokens==2.2.1
backcall==0.2.0
black==23.7.0
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
colorama==0.4.6
comm==0.1.4
contourpy==1.1.0
cycler==0.11.0
debugpy==1.6.7.post1
decorator==5.1.1
docker==6.1.3
executing==1.2.0
fonttools==4.42.1
grpcio==1.57.0
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.1
ipykernel==6.25.1
ipympl==0.9.3
ipython==8.12.2
ipython-genutils==0.2.0
ipywidgets==8.1.0
jedi==0.19.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyterlab-widgets==3.0.8
kiwisolver==1.4.5
lxml==4.9.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
mypy-extensions==1.0.0
nest-asyncio==1.5.7
numpy==1.24.4
packaging==23.1
pandas==2.0.3
parso==0.8.3
pathspec==0.11.2
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.10.0
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
Pygments==2.16.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
pywin32==306
PyYAML==6.0.1
pyzmq==25.1.1
requests==2.31.0
six==1.16.0
stack-data==0.6.2
tomli==2.0.1
tornado==6.3.3
traitlets==5.9.0
typing_extensions==4.7.1
tzdata==2023.3
urllib3==2.0.4
wcwidth==0.2.6
websocket-client==1.6.2
widgetsnbextension==4.0.8
zipp==3.16.2
```

**Comment by abhishekchitwar** [comment]
**Issue Resolved!**
Closing this issue! There is an issue in Report definition. 
Thanks!
