### ISSUE TITLE
Support reduction operations with vector quantity

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#1971]
>>> s.reduction.area_average(expression="Velocity", locations=s.setup.boundary_conditions.velocity_inlet)   

Error: fromScheme: double                                                                                           
Error Object: (0. 0. 0.)                                                                                            
Traceback (most recent call last):                                                                                  
  File "<stdin>", line 1, in <module>                                                                               
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\services\reduction.py", line 283, in area_average
    response = self.service.area_average(request)
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\services\error_handler.py", line 15, in func
    raise RuntimeError(ex.details()) from None
RuntimeError: The last request could not be completed because there is error in server.

>>> reduction.area_average(expr="Velocity", locations=s.setup.boundary_conditions.velocity_inlet)

Traceback (most recent call last):
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\solver\function\reduction.py", line 178, in _extent_expression
    numerator += val * extent                                                                                                    
TypeError: unsupported operand type(s) for +=: 'float' and 'list'                                                                
                                                                                                                                 
During handling of the above exception, another exception occurred:                                                              

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\solver\function\reduction.py", line 259, in area_average
    return _extent_average("Area", expr, locations, ctxt)
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\solver\function\reduction.py", line 201, in _extent_average
    return _extent_expression(f"{extent_name}Ave", extent_name, expr, locations, ctxt)
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\solver\function\reduction.py", line 181, in _extent_expression
    raise RuntimeError(val)
RuntimeError: [0.0, 0.0, 0.0]

**Comment by seanpearsonuk** [comment]
A 24R1 fix is going into Fluent.
