### ISSUE TITLE
Breakdown in v0.18.dev0 AttributeError: module 'ansys.api.fluent.v0.reduction_pb2' has no attribute 'SumRequest'

### ISSUE THREAD

**Issue by RebelYoung** [ansys/pyfluent#1981]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When I restart jupyter kernel, it break down in `import ansys.fluent.core as pyfluent`

```
(test) D:\young\py310>python
Python 3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import ansys.fluent.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\young\pyfluent\src\ansys\fluent\core\__init__.py", line 15, in <module>
    from ansys.fluent.core.launcher.launcher import (  # noqa: F401
  File "D:\young\pyfluent\src\ansys\fluent\core\launcher\launcher.py", line 25, in <module>
    from ansys.fluent.core.session_meshing import Meshing
  File "D:\young\pyfluent\src\ansys\fluent\core\session_meshing.py", line 6, in <module>
    from ansys.fluent.core.session_solver import Solver
  File "D:\young\pyfluent\src\ansys\fluent\core\session_solver.py", line 11, in <module>
    from ansys.fluent.core.services.reduction import Reduction, ReductionService
  File "D:\young\pyfluent\src\ansys\fluent\core\services\reduction.py", line 19, in <module>
    class ReductionService:
  File "D:\young\pyfluent\src\ansys\fluent\core\services\reduction.py", line 179, in ReductionService
    self, request: ReductionProtoModule.SumRequest
AttributeError: module 'ansys.api.fluent.v0.reduction_pb2' has no attribute 'SumRequest'. Did you mean: 'AreaRequest'?
```

```
(test) D:\young\py310> pip list
Package                               Version      Editable project location
------------------------------------- ------------ -------------------------
ansys-api-fluent                      0.3.16
ansys-api-platform-instancemanagement 1.0.0
ansys-fluent-core                     0.18.dev0    D:\young\pyfluent
ansys-fluent-visualization            0.7.1
ansys-platform-instancemanagement     1.1.2
```

### 📝 Steps to reproduce

restart jupyter kernel, it break down in `import ansys.fluent.core as pyfluent`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2023R1 and v 0.18.dev0

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
(test) D:\young\py310>pip freeze
ansys-api-fluent==0.3.16
ansys-api-platform-instancemanagement==1.0.0
-e git+https://github.com/ansys/pyfluent.git@b3ecee23959e3dafb7855d48d8ba052febe22598#egg=ansys_fluent_core
ansys-fluent-visualization==0.7.1
ansys-platform-instancemanagement==1.1.2
anyio==4.0.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.4.0
async-lru==2.0.4
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
colorama==0.4.6
comm==0.1.4
contourpy==1.1.0
cycler==0.11.0
debugpy==1.8.0
decorator==5.1.1
defusedxml==0.7.1
docker==6.1.3
exceptiongroup==1.1.3
executing==1.2.0
fastjsonschema==2.18.0
fonttools==4.42.1
fqdn==1.5.1
grpcio==1.58.0
grpcio-health-checking==1.48.2
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
ipykernel==6.25.2
ipython==8.15.0
ipython-genutils==0.2.0
ipywidgets==8.1.1
isoduration==20.11.0
jedi==0.19.0
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.3.1
jupyter_core==5.3.1
jupyter_server==2.7.3
jupyter_server_terminals==0.4.4
jupyterlab==4.0.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.0
kiwisolver==1.4.5
lxml==4.9.3
MarkupSafe==2.1.3
matplotlib==3.7.3
matplotlib-inline==0.1.6
mistune==3.0.1
nbclient==0.8.0
nbconvert==7.8.0
nbformat==5.9.2
nest-asyncio==1.5.7
notebook==7.0.3
notebook_shim==0.2.3
numpy==1.25.2
overrides==7.4.0
packaging==23.1
pandas==2.1.0
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.10.0
pointwise-glyph-client==2.0.10
pooch==1.7.0
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
pycparser==2.21
Pygments==2.16.1
pyparsing==3.1.1
PySide6==6.5.2
PySide6-Addons==6.5.2
PySide6-Essentials==6.5.2
python-dateutil==2.8.2
python-json-logger==2.0.7
pytz==2023.3.post1
pyvista==0.42.1
pyvistaqt==0.11.0
pywin32==306
pywinpty==2.0.11
PyYAML==6.0.1
pyzmq==25.1.1
qtconsole==5.4.4
QtPy==2.4.0
referencing==0.30.2
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.10.3
scipy==1.11.2
scooby==0.7.2
Send2Trash==1.8.2
shiboken6==6.5.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.5
stack-data==0.6.2
terminado==0.17.1
tinycss2==1.2.1
tomli==2.0.1
tornado==6.3.3
traitlets==5.9.0
typing_extensions==4.7.1
tzdata==2023.3
uri-template==1.3.0
urllib3==2.0.4
vtk==9.2.6
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.3
widgetsnbextension==4.0.9
zipp==3.16.2
```

**Comment by RebelYoung** [comment]
I create a new conda enviroment and install pyfluent by clone repo.
When `python codegen/allapigen.py`,
```
(py310) PS D:\young\pyfluent> python codegen/allapigen.py
Traceback (most recent call last):
  File "D:\young\pyfluent\codegen\allapigen.py", line 6, in <module>
    import datamodelgen
  File "D:\young\pyfluent\codegen\datamodelgen.py", line 8, in <module>
    from ansys.fluent.core.session import BaseSession as Session
  File "D:\young\pyfluent\src\ansys\fluent\core\__init__.py", line 15, in <module>
    from ansys.fluent.core.launcher.launcher import (  # noqa: F401
  File "D:\young\pyfluent\src\ansys\fluent\core\launcher\launcher.py", line 25, in <module>
    from ansys.fluent.core.session_meshing import Meshing
  File "D:\young\pyfluent\src\ansys\fluent\core\session_meshing.py", line 6, in <module>
    from ansys.fluent.core.session_solver import Solver
  File "D:\young\pyfluent\src\ansys\fluent\core\session_solver.py", line 11, in <module>
    from ansys.fluent.core.services.reduction import Reduction, ReductionService
  File "D:\young\pyfluent\src\ansys\fluent\core\services\reduction.py", line 19, in <module>
    class ReductionService:
  File "D:\young\pyfluent\src\ansys\fluent\core\services\reduction.py", line 179, in ReductionService
    self, request: ReductionProtoModule.SumRequest
AttributeError: module 'ansys.api.fluent.v0.reduction_pb2' has no attribute 'SumRequest'. Did you mean: 'AreaRequest'?
```

**Comment by RebelYoung** [comment]
`python codegen/allapigen.py` or `import ansys.fluent.core as pyfluent`
in `reduction.py`
`from ansys.api.fluent.v0 import reduction_pb2 as ReductionProtoModule`, connect to another conda enviroment , whose pyfluent version is different.

**Comment by RebelYoung** [comment]
`python codegen/allapigen.py` or `import ansys.fluent.core as pyfluent`
in `reduction.py`
`from ansys.api.fluent.v0 import reduction_pb2 as ReductionProtoModule`, connect to another conda enviroment , whose pyfluent version is different.

**Comment by RebelYoung** [comment]
@prmukherj

**Comment by RebelYoung** [comment]
@prmukherj I have try many conda envs and pyfluent versions, include ’py39+v0.17.1`, `py310+branch\add_sum...`. All of them failed import the pyfluent package.
In ’py39+v0.17.1`, there are new line in reduction_pb2.py, but it still broke down.
```
>>> import ansys.fluent.core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\__init__.py", line 15, in <module>
    from ansys.fluent.core.launcher.launcher import (  # noqa: F401
ule>
    from ansys.fluent.core.session_meshing import Meshing
  File "C:\Users\Admin\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\session_meshing.py", line 6, in <module>
    from ansys.fluent.core.session_solver import Solver
  File "C:\Users\Admin\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\session_solver.py", line 11, in <module>
    from ansys.fluent.core.services.reduction import Reduction, ReductionService
  File "C:\Users\Admin\miniconda3\envs\py39\lib\site-packages\ansys\fluent\core\services\reduction.py", line 7, in <module>
    from ansys.api.fluent.v0 import reduction_pb2 as ReductionProtoModule
  File "C:\Users\Admin\miniconda3\envs\py39\lib\site-packages\ansys\api\fluent\v0\reduction_pb2.py", line 62, in <module>
    _SumREQUEST = DESCRIPTOR.message_types_by_name['SumRequest']
KeyError: 'SumRequest'
```

**Comment by prmukherj** [comment]
@seanpearsonuk, already fixed. Will be available in next release.
