### ISSUE TITLE
Documentation search feature isn't working

### ISSUE THREAD

**Issue by raph-luc** [ansys/pyfluent#2093]
https://fluent.docs.pyansys.com/version/dev/search.html

Related:
https://github.com/ansys/pyfluent/pull/2040
https://github.com/ansys/pyfluent/pull/2024

Nightly dev doc build is failing:
https://github.com/ansys/pyfluent/actions/workflows/nightly-dev-doc-build.yml
```
File "/home/runner/.local/lib/python3.10/site-packages/ansys/tools/meilisearch/templates/__init__.py", line 79, in render_template
    if "localhost" in urls[0]:
IndexError: list index out of range
```

**Comment by raph-luc** [comment]
That issue was fixed, but a new one cropped up:
<details><summary> Traceback</summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/runner/.local/lib/python3.10/site-packages/scraper/src/documentation_spider.py", line 178, in parse_from_start_url
    self.add_records(response, from_sitemap=False)
  File "/home/runner/.local/lib/python3.10/site-packages/scraper/src/documentation_spider.py", line 152, in add_records
    self.meilisearch_helper.add_records(records, response.url, from_sitemap)
  File "/home/runner/.local/lib/python3.10/site-packages/scraper/src/meilisearch_helper.py", line 123, in add_records
    self.meilisearch_index.add_documents(cleaned_records)
  File "/home/runner/.local/lib/python3.10/site-packages/meilisearch/index.py", line 381, in add_documents
    add_document_task = self.http.post(url, documents)
  File "/home/runner/.local/lib/python3.10/site-packages/meilisearch/_httprequests.py", line 73, in post
    return self.send_request(requests.post, path, body, content_type)
  File "/home/runner/.local/lib/python3.10/site-packages/meilisearch/_httprequests.py", line 57, in send_request
    return self.__validate(request)
  File "/home/runner/.local/lib/python3.10/site-packages/meilisearch/_httprequests.py", line 110, in __validate
    raise MeilisearchApiError(str(err), request) from err
meilisearch.errors.MeilisearchApiError: MeilisearchApiError. Error code: internal. Error message: MDB_PANIC: Update of meta page failed or environment had fatal error Error documentation: https://docs.meilisearch.com/errors#internal Error type: internal
127.0.0.1 - - [17/Oct/2023 07:49:55] "GET /api/solver/_autosummary/settings/print_thread_clusters.html HTTP/1.1" 200 -
2023-10-17 07:49:56 [scrapy.core.scraper] ERROR: Spider error processing <GET http://localhost:8000/api/solver/_autosummary/settings/maximum_allowed_effctive_relaxation.html> (referer: None)
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/meilisearch/_httprequests.py", line 107, in __validate
    request.raise_for_status()
  File "/home/runner/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://backend.search.pyansys.com/indexes/pyfluent-vdev/documents

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/runner/.local/lib/python3.10/site-packages/scraper/src/documentation_spider.py", line 178, in parse_from_start_url
    self.add_records(response, from_sitemap=False)
  File "/home/runner/.local/lib/python3.10/site-packages/scraper/src/documentation_spider.py", line 152, in add_records
    self.meilisearch_helper.add_records(records, response.url, from_sitemap)
  File "/home/runner/.local/lib/python3.10/site-packages/scraper/src/meilisearch_helper.py", line 123, in add_records
    self.meilisearch_index.add_documents(cleaned_records)
  File "/home/runner/.local/lib/python3.10/site-packages/meilisearch/index.py", line 381, in add_documents
    add_document_task = self.http.post(url, documents)
  File "/home/runner/.local/
```

</details>

Now causing issues for nightly and 0.18 release:
[Nightly Development Documentation Build](https://github.com/ansys/pyfluent/actions/runs/6542343963/job/17767696608#step:14:161984)
[Release Documentation Build](https://github.com/ansys/pyfluent/actions/runs/6514583214/job/17697520257#step:20:130140)

**Comment by Revathyvenugopal162** [comment]
https://github.com/ansys/pyfluent/actions/runs/6556026309 the dev docs is working fine from my side today.

**Comment by raph-luc** [comment]
So nothing was changed but a re-build passed? Can confirm dev doc search now works as well

Good old "just reboot and try it again" :) 

Waiting to see if the release docs now work as well, before closing the issues

**Comment by raph-luc** [comment]
The release docs build passed, but now neither dev docs nor release docs meilisearch works:
![search_not_working](https://github.com/ansys/pyfluent/assets/132297401/9bd7bd6b-ce23-4f1b-89a5-b4a7a9ab9da9)

**Comment by mkundu1** [comment]
The search results appear if I wait for a few seconds after entering the search string. I checked pyaedt docs behaves in the same way. Also, building the index takes more than 4 hours.

@Revathyvenugopal162 Can anything be done for both slowness?

**Comment by raph-luc** [comment]
Thanks @mkundu1, you're absolutely right. From some quick tests it seems it can take 6-10+ seconds sometimes, you have to not click or do anything and just wait after typing the search string. If you press enter or click elsewhere then it doesn't work as you can see in my GIF above.

Exact same issues in the PyAEDT docs search:
https://aedt.docs.pyansys.com/version/stable/index.html

This looks like a straight downgrade from the search function we had before, for example see:
https://fluent.docs.pyansys.com/version/0.17/search.html which works great in my opinion.

Pressing enter to get the results immediately feels better to me than having to wait without clicking anything.

**Comment by Revathyvenugopal162** [comment]
> Thanks @mkundu1, you're absolutely right. From some quick tests it seems it can take several seconds sometimes, you have to not click or do anything and just wait after typing the search string. If you press enter or click elsewhere then it doesn't work as in my GIF above.
> 
> As Mainak noted, exact same issues in the PyAEDT docs search: https://aedt.docs.pyansys.com/version/stable/index.html
> 
> This looks like a straight downgrade from the search function we had before, for example see: https://fluent.docs.pyansys.com/version/0.17/search.html which works great in my opinion and is always pretty much instant.
> 
> Pressing enter to get the results immediately feels better to me than having to wait without clicking anything.
> 
> Also, why is there this dropbox: ![image](https://user-images.githubusercontent.com/132297401/276394126-bb646874-b805-4e67-a7d6-61aad41898b3.png) Is this going to be integrated with other PyAnsys repos?
> 
> Update: given the issues and slowness described above, the plan for now is to revert to the previous search methodology, and try pymeilisearch again later.

yes, it is slow because pyfluent have lots of document to search. We are looking for the solution to make it fast. We will update to you . pinging @jorgepiloto

**Comment by raph-luc** [comment]
Thanks for the explanation @Revathyvenugopal162, note it is not only slow in PyFluent, it is also somewhat slow in PyAEDT https://aedt.docs.pyansys.com/ (at least the first time you use it) 

And if you press enter or click anywhere else before results show up, then the search breaks, as in my GIF above, same issue for both repositories: https://github.com/ansys/pyfluent/issues/2093#issuecomment-1769221964

**Comment by raph-luc** [comment]
Working correctly now: 
https://fluent.docs.pyansys.com/version/dev/search.html
https://fluent.docs.pyansys.com/version/stable/search.html

We can try the new search features again in the future
