### ISSUE TITLE
solver.solution.iterate makes too many rpc calls before throwing AttributeError

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2218]
The following code makes 18 trips to the server as shown in the log. This slows down user interaction in pyconsole implemented using pyfluent.
```
>>> solver.solution.iterate
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "d:\ANSYSDev\PyFluentDev\pyfluent\env\Lib\site-packages\ansys\fluent\core\solver\flobject.py", line 554, in __getattribute__
    return super().__getattribute__(name)
AttributeError: iterate is not an allowed Settings objects name.
The most similar names are: monitor.
```
Logging output:
```
2023-11-08 11:18:44,933 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetStaticInfo, request = {'root': 'fluent'}
2023-11-08 11:18:45,952 pyfluent.networking   DEBUG    GRPC_TRACE: message partially hidden, 1604922 bytes > 1000 bytes limit. To see the full message, set PYFLUENT_GRPC_LOG_BYTES_LIMIT to 0.
2023-11-08 11:18:45,953 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'info': {'type': 'group', 'children': [{'name': 'file', 'value': {'type': 'group', 'children': [{'name': 'single-precision-coordinates?', 'value': {'type': 'boolean', 'help': 'Indicate whether to wri < ... > network latency.'}}, {'name': 'bandwidth', 'value': {'type': 'command', 'help': 'Show network bandwidth.'}}]}}], 'commands': [{'name': 'exit', 'value': {'type': 'command', 'help': 'Exit program.'}}]}}
2023-11-08 11:18:49,736 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent'}, 'attrs': ['active?']}
2023-11-08 11:18:54,523 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:54,524 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:54,616 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:54,616 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/methods'}, 'attrs': ['active?']}
2023-11-08 11:18:54,679 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
2023-11-08 11:18:54,681 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:54,728 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:54,729 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/controls'}, 'attrs': ['active?']}
2023-11-08 11:18:54,823 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
2023-11-08 11:18:54,824 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:54,899 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:54,900 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/report-definitions'}, 'attrs': ['active?']}
2023-11-08 11:18:54,978 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
2023-11-08 11:18:54,979 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:55,057 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:55,058 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/monitor'}, 'attrs': ['active?']}
2023-11-08 11:18:55,119 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
2023-11-08 11:18:55,120 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:55,230 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:55,231 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/cell-registers'}, 'attrs': ['active?']}
2023-11-08 11:18:55,294 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
2023-11-08 11:18:55,294 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:55,373 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:55,374 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/initialization'}, 'attrs': ['active?']}
2023-11-08 11:18:55,498 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
2023-11-08 11:18:55,499 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:55,560 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:55,561 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/calculation-activity'}, 'attrs': ['active?']}
2023-11-08 11:18:55,576 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
2023-11-08 11:18:55,576 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution'}, 'attrs': ['active?']}
2023-11-08 11:18:55,624 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': True}}}}}
2023-11-08 11:18:55,625 pyfluent.networking   DEBUG    GRPC_TRACE: RPC = /ansys.api.fluent.v0.settings.Settings/GetAttrs, request = {'pathInfo': {'root': 'fluent', 'path': 'solution/run-calculation'}, 'attrs': ['active?']}
2023-11-08 11:18:55,705 pyfluent.networking   DEBUG    GRPC_TRACE: response = {'values': {'valueMap': {'m': {'active?': {'boolean': False}}}}}
```
We shall investigate why this code makes so many rpc calls and try to reduce them.

**Comment by mkundu1** [comment]
I'll look into this as a similar issue exists for pyconsole autocompleter.

**Comment by mkundu1** [comment]
This issue is resolved in the latest main branch.
