### ISSUE TITLE
inspect.signature(solver.parameters)  throws error

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2345]
```
>>> import ansys.fluent.core as pyfluent
>>> solver = pyfluent.launch_fluent()
>>> import inspect
>>> inspect.signature(solver.file)
<Signature (*args, **kwargs)>
>>> inspect.signature(solver.parameters) 
Traceback (most recent call last):
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 586, in __getattribute__
    raise RuntimeError(f"'{self.python_path}' is currently not active")
AttributeError: 'parameters' object has no attribute '__wrapped__'. Did you mean: '__weakref__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mkundu\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 3254, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped,
  File "C:\Users\mkundu\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 3002, in from_callable
    return _signature_from_callable(obj, sigcls=cls,
  File "C:\Users\mkundu\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 2412, in _signature_from_callable
    obj = unwrap(obj, stop=(lambda f: hasattr(f, "__signature__")
  File "C:\Users\mkundu\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 639, in unwrap
    while _is_wrapper(func):
  File "C:\Users\mkundu\AppData\Local\Programs\Python\Python310\lib\inspect.py", line 633, in _is_wrapper
    return hasattr(f, '__wrapped__') and not stop(f)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 588, in __getattribute__
    return super().__getattribute__(name)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 568, in _get_parent_of_active_child_names
    parents = ""
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 517, in get_active_child_names
    for child in self.child_names:
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 584, in __getattribute__
    if self.is_active() is False:
RuntimeError: '<session>.parameters' is currently not active
```
The method `inspect.signature` is used in the autocompleter code in Fluent. I'm adding a try-catch in the Fluent to avoid the error, but  that method is generally expected to work in Python.

**Comment by mkundu1** [comment]
Closing as not important (not worth changing the current code)
