### ISSUE TITLE
hasattr(meshing.workflow, ...) is always true

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2397]
```
>>> import ansys.fluent.core as pyfluent
>>> meshing = pyfluent.launch_fluent(mode="meshing")
>>> meshing.workflow
<ansys.fluent.core.meshing.meshing_workflow.MeshingWorkflow object at 0x0000027338FCCA60>
>>> hasattr(meshing.workflow, "xyz")
True
>>> meshing.workflow.xyz is None
True
```
Found during triaging an issue PyConsole Autocompleter.

**Comment by prmukherj** [comment]
@mkundu1, I cannot reproduce this issue. I am getting the expected beavior.

>>> hasattr(meshing.workflow, "xyz")        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\workflow.py", line 909, in __getattr__
    obj = self._attr_from_wrapped_workflow(
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\workflow.py", line 951, in _attr_from_wrapped_workflow
    result = getattr(self._workflow, attr)
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 1804, in __getattr__
    return self._get_child(name)
  File "C:\ANSYSDev\PyFluent_Dev_01\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 1793, in _get_child
    raise LookupError(
LookupError: xyz is not found at path

**Comment by mkundu1** [comment]
@prmukherj I have added a test in PR #2399 which is currently failing.

**Comment by prmukherj** [comment]
@mkundu1, after initial triaging I figured that the issue is occurring only if codegen has been run before.
