### ISSUE TITLE
Read/Write commands failing after switch_to_solution_mode()

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#2475]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Commands such as `solver.file.write(file_type="case", file_name="<casename>")` are failing with the below error. The issue occurs after the solver session was created by switching from meshing mode and meshing mode was launched using a pyfluent journal with the `flglobals` launch method
```
Error: wta(1st) to string->symbol
Traceback (most recent call last):
  File "/tutorials/headlamp_rad_tut_s1.XoXISg/headlamp_rad_tut_s1.py", line 74, in <module>
    solver.file.write(file_type = "case", file_name = "headlamp.cas.h5")
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 1375, in __call__
    return self.execute_command(**kwds)
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 1344, in execute_command
    argument.after_execute(value)
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 299, in after_execute
    self._do_after_execute(value)
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 628, in _do_after_execute
    self.remote_file_handler.download(file_name=value)
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 156, in remote_file_handler
    return self._parent.remote_file_handler
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 156, in remote_file_handler
    return self._parent.remote_file_handler
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 853, in __getattribute__
    return super().__getattribute__(name)
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 156, in remote_file_handler
    return self._parent.remote_file_handler
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 855, in __getattribute__
    self._get_parent_of_active_child_names(name)
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 823, in _get_parent_of_active_child_names
    if hasattr(getattr(self, parent), str(name)):
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 853, in __getattribute__
    return super().__getattribute__(name)
  File "/.venv/lib/python3.10/site-packages/ansys/fluent/core/solver/flobject.py", line 156, in remote_file_handler
    return self._parent.remote_file_handler
    ...
    ...
    ...
        raise ex from None
RuntimeError: wta(1st) to string->symbol
Error Object: #[free (7 cells)]
Error Object: #[free (7 cells)]


```
Issue affects multiple regression tests

### 📝 Steps to reproduce

Launch pyfluent solver session
Read case/mesh
Write using command such as;
`solver.file.write(File_type="case", file_name="<casename>")`
Open new meshing py session and read mesh;
```
flglobals = pyfluent.setup_for_fluent(mode="meshing")
globals().update(flglobals)
meshing.meshing.File.ReadMesh(...)
```
Switch to solution mode and write file;
```
meshing.switch_to_solver()
solver.file.write(...)

```

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

v242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
absl-py==2.1.0
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core @ file:///home/staff/jomiller/.venv/pyfluent
ansys-fluent-parametric @ file:///home/staff/jomiller/.venv/pyfluent-parametric
ansys-fluent-visualization @ file:///home/staff/jomiller/.venv/pyfluent-visualization
ansys-platform-instancemanagement==1.1.2
ansys-units==0.3.0
asttokens==2.4.1
astunparse==1.6.3
bcrypt==4.1.2
beartype==0.17.2
blinker==1.7.0
cachetools==5.3.2
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.2.0
cryptography==42.0.3
cycler==0.12.1
dash==2.15.0
dash-bootstrap-components==1.5.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
decorator==5.1.1
docker==7.0.0
et-xmlfile==1.1.0
exceptiongroup==1.2.0
executing==2.0.1
Flask==3.0.2
flatbuffers==23.5.26
fonttools==4.49.0
gast==0.5.4
google-auth==2.28.0
google-auth-oauthlib==1.2.0
google-pasta==0.2.0
grpcio==1.60.1
grpcio-health-checking==1.48.2
h5py==3.10.0
idna==3.6
imageio==2.34.0
importlib-metadata==7.0.1
iniconfig==2.0.0
ipython==8.21.0
itsdangerous==2.1.2
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
kaleido==0.2.1
keras==2.15.0
kiwisolver==1.4.5
libclang==16.0.6
lxml==5.1.0
Markdown==3.5.2
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline==0.1.6
ml-dtypes==0.2.0
nest-asyncio==1.6.0
numpy==1.26.4
oauthlib==3.2.2
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.2
pandas==2.2.0
paramiko==3.4.0
paramiko-expect==0.3.5
parso==0.8.3
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.2.0
plotly==5.19.0
pluggy==1.4.0
pooch==1.8.0
prompt-toolkit==3.0.43
protobuf==3.20.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.17.2
PyNaCl==1.5.0
pyparsing==3.1.1
PySide6==6.6.2
PySide6_Addons==6.6.2
PySide6_Essentials==6.6.2
pytest==8.0.1
python-dateutil==2.8.2
python-pptx==0.6.23
pytz==2024.1
pyvista==0.43.3
pyvistaqt==0.11.0
PyYAML==6.0.1
QtPy==2.4.1
requests==2.31.0
requests-oauthlib==1.3.1
retrying==1.3.4
rsa==4.9
scikit-learn==1.4.1.post1
scipy==1.12.0
scooby==0.9.2
seaborn==0.13.2
shiboken6==6.6.2
six==1.16.0
stack-data==0.6.3
tenacity==8.2.3
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorflow==2.15.0.post1
tensorflow-estimator==2.15.0
tensorflow-io-gcs-filesystem==0.36.0
termcolor==2.4.0
threadpoolctl==3.3.0
tomli==2.0.1
traitlets==5.14.1
typing_extensions==4.9.0
tzdata==2024.1
urllib3==2.2.1
vtk==9.3.20230807rc0
wcwidth==0.2.13
Werkzeug==3.0.1
wrapt==1.14.1
xgboost==2.0.3
XlsxWriter==3.2.0
zipp==3.17.0
```

**Comment by millerj97** [comment]
@mkundu1 have shared a script with you which should be reproducible

**Comment by hpohekar** [comment]
@mkundu1 @millerj97 

I'm not able to reproduce this issue.

```
(310) PS D:\pyfluent> python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ansys.fluent.core import launch_fluent
>>> from ansys.fluent.core import examples
>>> import_file_name = examples.download_file("mixing_elbow.msh.h5", "pyfluent/mixing_elbow")
File already exists. File path:
C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\mixing_elbow.msh.h5
>>> solver = launch_fluent()
>>> solver.file.read(file_type="mesh", file_name=import_file_name)
Fast-loading "D:\ANSYSDev\vNNN\fluent\fluent24.2\\addons\afd\lib\hdfio.bin"
Done.

AAPQ13pUvWxQtxN has other FLUENT parallel processes running.                       Process affinity not being set.

Reading from AAPQ13pUvWxQtxN:"C:\Users\hpohekar\AppData\Local\Ansys\ansys_fluent_core\examples\mixing_elbow.msh.h5" in NODE0 mode ...
  Reading mesh ...
       17822 cells,     1 cell zone  ...
          17822 mixed cells,  zone id: 87
       91581 faces,     7 face zones ...
           2001 polygonal symmetry faces,  zone id: 29
             55 polygonal velocity-inlet faces,  zone id: 30
            152 polygonal velocity-inlet faces,  zone id: 31
            155 polygonal pressure-outlet faces,  zone id: 32
            268 polygonal wall faces,  zone id: 33
           2168 polygonal wall faces,  zone id: 34
          86782 mixed interior faces,  zone id: 89
       66417 nodes,     3 node zones ...

Building...
     mesh
     materials,
     interface,
     domains,
     zones,
        Skipping thread 20 of domain 1 (not referenced by grid).
        Skipping thread 21 of domain 1 (not referenced by grid).
        Skipping thread 22 of domain 1 (not referenced by grid).
        Skipping thread 23 of domain 1 (not referenced by grid).
        Skipping thread 24 of domain 1 (not referenced by grid).
        Skipping thread 25 of domain 1 (not referenced by grid).
        Skipping thread 26 of domain 1 (not referenced by grid).
        Skipping thread 27 of domain 1 (not referenced by grid).
        Skipping thread 28 of domain 1 (not referenced by grid).
        symmetry-xyplane
        hot-inlet
        cold-inlet
        outlet
        wall-inlet
        wall-elbow
        interior--elbow-fluid
        elbow-fluid
     parallel,
Done.
Mesh is now scaled to meters.
True
>>> solver.file.write(file_type="case", file_name="try_solver_write.cas.h5")

Writing to AAPQ13pUvWxQtxN:"D:\pyfluent\try_solver_write.cas.h5" in NODE0 mode and compression level 1 ...
Grouping cells for Laplace smoothing ...
  Done.       17822 cells,     1 zone  ...
       91581 faces,     7 zones ...
       66417 nodes,     1 zone  ...
  Done.
Done.
True
>>> meshing = launch_fluent(mode="meshing")
>>> meshing.meshing.File.ReadMesh(FileName=import_file_name)
True
>>> solver_switch = meshing.switch_to_solver()
>>> solver_switch.file.write(file_type="case", file_name="try_solver_switch_write.cas.h5")
True
>>> 
```

Both files are written correctly.

![image](https://github.com/ansys/pyfluent/assets/106588300/10c23e0a-df37-4ea9-a936-1ab5255d8fa0)

**Comment by mkundu1** [comment]
@hpohekar Can you please try with the following script?
```
flglobals = pyfluent.setup_for_fluent(mode="meshing")
globals().update(flglobals)
meshing.meshing.File.ReadMesh(...)
meshing.switch_to_solver()
solver.file.write(...)
```
This is how a Python journal is saved from Fluent.

**Comment by hpohekar** [comment]
> @hpohekar Can you please try with the following script?
> 
> ```
> flglobals = pyfluent.setup_for_fluent(mode="meshing")
> globals().update(flglobals)
> meshing.meshing.File.ReadMesh(...)
> meshing.switch_to_solver()
> solver.file.write(...)
> ```
> 
> This is how a Python journal is saved from Fluent.

@mkundu1 

I discussed this issue with @millerj97 and the script was working on his system. He will update about latest regression tests results.

**Comment by millerj97** [comment]
> > @hpohekar Can you please try with the following script?
> > ```
> > flglobals = pyfluent.setup_for_fluent(mode="meshing")
> > globals().update(flglobals)
> > meshing.meshing.File.ReadMesh(...)
> > meshing.switch_to_solver()
> > solver.file.write(...)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is how a Python journal is saved from Fluent.
> 
> @mkundu1
> 
> I discussed this issue with @millerj97 and the script was working on his system. He will update about latest regression tests results.

@hpohekar the regressions are still failing, I believe @mkundu1 point about the python journal was missing from the script I tried earlier too, so we need flglobals in the scripts

**Comment by hpohekar** [comment]
> file_type="case", file_name="try_solver_switch_write.cas.h5"

I tried this. It works fine.

![image](https://github.com/ansys/pyfluent/assets/106588300/9098cc27-1e13-4742-a84a-c8c392e9e4a9)

![image](https://github.com/ansys/pyfluent/assets/106588300/9abda4b3-e877-449a-92fe-8dab8009d8f6)
