### ISSUE TITLE
solver.results.graphics.volumes() is failing in latest image

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2526]
```
>>> solver.results.graphics.contour()
>>> solver.results.graphics.volumes()

Error: GENERAL-CAR-CDR: invalid argument [1]: improper list
Error Object: #f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 593, in __call__
    return self.get_state()
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 597, in get_state
    return self.to_python_keys(self.flproxy.get_var(self.path))
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\settings.py", line 112, in _fn
    return fn(self, *args, **kwds)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\settings.py", line 184, in get_var
    response = self._service_impl.get_var(request)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\settings.py", line 41, in get_var
    return self.__stub.GetVar(request, metadata=self.__metadata)
  File "C:\Users\mkundu\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "C:\Users\mkundu\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\grpc\_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 122, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 112, in _intercept_call
    raise ex from None
RuntimeError: GENERAL-CAR-CDR: invalid argument [1]: improper list
Error Object: #f
>>> solver.results.graphics()

Error: GENERAL-CAR-CDR: invalid argument [1]: improper list
Error Object: #f
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 849, in __call__
    return self.get_state()
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\solver\flobject.py", line 597, in get_state
    return self.to_python_keys(self.flproxy.get_var(self.path))
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\settings.py", line 112, in _fn
    return fn(self, *args, **kwds)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\settings.py", line 184, in get_var
    response = self._service_impl.get_var(request)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\settings.py", line 41, in get_var
    return self.__stub.GetVar(request, metadata=self.__metadata)
  File "C:\Users\mkundu\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "C:\Users\mkundu\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\grpc\_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 122, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\interceptors.py", line 112, in _intercept_call
    raise ex from None
RuntimeError: GENERAL-CAR-CDR: invalid argument [1]: improper list
Error Object: #f
```
Also seen in PyConsole.

**Comment by mkundu1** [comment]
This is reproducible with Fluent develop branch, but with the docker image.

**Comment by mkundu1** [comment]
Fluent side issue is created.

**Comment by mkundu1** [comment]
Resolved in the latest image
