### ISSUE TITLE
logging.py and other files cause pyfluent crash

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#2547]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

If the user includes files such as `logging.py` or `ansys.py` in their working directory, the pyfluent session will not run, with the following error message;
```
Traceback (most recent call last):
  File "\mypyfluent.py", line 1, in <module>
    import ansys.fluent.core as pyfluent
  File "\newenv\lib\site-packages\ansys\fluent\core\__init__.py", line 9, in <module>
    import ansys.fluent.core.logging as logging
  File "\newenv\lib\site-packages\ansys\fluent\core\logging.py", line 6, in <module>
    import logging.config
ModuleNotFoundError: No module named 'logging.config'; 'logging' is not a package

```

### 📝 Steps to reproduce

- In working directory create a file called `logging.py`
- use basic script such as;
```
import ansys.fluent.core as pyfluent

solver = pyfluent.launch_fluent()

```
- run the script `python basic_script.py`
- see previous error reported
- delete `logging.py` file and run script again

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

v242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
absl-py==2.1.0
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.0.0
ansys-fluent-core==0.20.dev7
-e s:\jomiller\pyfluent-parametric
-e s:\jomiller\pyfluent-visualization
ansys-platform-instancemanagement==1.1.2
ansys-units==0.3.1
asttokens==2.4.1
astunparse==1.6.3
bcrypt==4.1.2
beartype==0.17.2
blinker==1.7.0
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
contourpy==1.2.0
cryptography==42.0.5
cycler==0.12.1
dash==2.16.1
dash-bootstrap-components==1.5.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
decorator==5.1.1
docker==7.0.0
et-xmlfile==1.1.0
exceptiongroup==1.2.0
executing==2.0.1
Flask==3.0.2
flatbuffers==24.3.6
fonttools==4.49.0
gast==0.5.4
google-auth==2.28.1
google-auth-oauthlib==1.2.0
google-pasta==0.2.0
grpcio==1.62.0
grpcio-health-checking==1.48.2
h5py==3.10.0
idna==3.6
imageio==2.34.0
importlib-metadata==7.0.1
ipython==8.22.2
itsdangerous==2.1.2
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
kaleido==0.2.1
keras==2.15.0
kiwisolver==1.4.5
libclang==16.0.6
lxml==5.1.0
Markdown==3.5.2
MarkupSafe==2.1.5
matplotlib==3.8.3
matplotlib-inline==0.1.6
ml-dtypes==0.2.0
nest-asyncio==1.6.0
numpy==1.26.4
oauthlib==3.2.2
openpyxl==3.1.2
opt-einsum==3.3.0
packaging==23.2
pandas==2.2.1
paramiko==3.4.0
paramiko-expect==0.3.5
parso==0.8.3
pillow==10.2.0
platformdirs==4.2.0
plotly==5.19.0
pooch==1.8.1
prompt-toolkit==3.0.43
protobuf==3.20.3
psutil==5.9.8
pure-eval==0.2.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
Pygments==2.17.2
PyNaCl==1.5.0
pyparsing==3.1.2
PySide6==6.6.2
PySide6_Addons==6.6.2
PySide6_Essentials==6.6.2
python-dateutil==2.9.0.post0
python-pptx==0.6.23
pytz==2024.1
pyvista==0.43.3
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
QtPy==2.4.1
requests==2.31.0
requests-oauthlib==1.3.1
retrying==1.3.4
rsa==4.9
scikit-learn==1.4.1.post1
scipy==1.12.0
scooby==0.9.2
seaborn==0.13.2
shiboken6==6.6.2
six==1.16.0
stack-data==0.6.3
tenacity==8.2.3
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorflow==2.15.0
tensorflow-estimator==2.15.0
tensorflow-intel==2.15.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.4.0
threadpoolctl==3.3.0
traitlets==5.14.1
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
vtk==9.3.20230807rc0
wcwidth==0.2.13
Werkzeug==3.0.1
wrapt==1.14.1
xgboost==2.0.3
XlsxWriter==3.2.0
zipp==3.17.0
```

**Comment by millerj97** [comment]
@raph-luc

**Comment by raph-luc** [comment]
Thanks @millerj97

Note also this can be reproduced directly in a Python interpreter, e.g. with a local empty `ansys.py` file:
![image](https://github.com/ansys/pyfluent/assets/132297401/c2d4527c-2521-4ed2-a55a-406a3a92740c)

**Comment by mkundu1** [comment]
This is a standard Python behaviour - https://docs.python.org/3/library/sys_path_init.html#the-initialization-of-the-sys-path-module-search-path. I think user will be aware of this and this is not a defect.

**Comment by raph-luc** [comment]
I don't know if there is much that we can do about this, but a large variety of module names in the current working directory will conflict with PyFluent and result in weird errors/undefined behavior, for example a few are:
```
ansys.py
logging.py
pydoc.py
copy.py
socket.py
warnings.py
subprocess.py
docker.py
inspect.py
zipfile.py
requests.py
codecs.py
tempfile.py
json.py
...
```

And the errors can be quite unhelpful too, for example creating an empty `json.py` and then trying to `import ansys.fluent.core as pf`, the traceback starts with:
```
Traceback (most recent call last):
  File "E:\ansysdev\venv_default\Lib\site-packages\requests\compat.py", line 11, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```
