### ISSUE TITLE
Unconfigured upload/download to be handled gracefully

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2557]
Calling `solver.download()` when no service is configured leads to a low-level exception. This should be handled without any side effects, Apologies if this is already covered by another issue.
```
>>> solver = pf.launch_fluent(show_gui=True)
C:\ANSYSDev\pyfluent\.venv4\Lib\site-packages\ansys\fluent\core\launcher\launcher.py:266: PyFluentDeprecationWarning: 'show_gui' is deprecated, use 'ui' instead
  warnings.warn(
>>> solver.upload
<bound method BaseSession.upload of <ansys.fluent.core.session_solver.Solver object at 0x000002AF43476B60>>
>>> solver.upload("bob")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ANSYSDev\pyfluent\.venv4\Lib\site-packages\ansys\fluent\core\session.py", line 287, in upload
    return self._file_transfer_service.upload_file(file_name)
AttributeError: 'NoneType' object has no attribute 'upload_file'
```

**Comment by seanpearsonuk** [comment]
N.b. I have labeled it as console_integration but in fact it won't be that critical, due to other changes.

**Comment by seanpearsonuk** [comment]
@hpohekar What I meant was that `upload()` and `download()` should be no-ops if no service is available. This is because of te requirement to directly reuse scripts in Lab / desktop.
