### ISSUE TITLE
Cannot launch pyfluent on shared drive when user does not have read/write permissions

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#2588]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Launching pyfluent standalone on a network drive directory that the user does not have read/write permissions causes the following error;
```
>>> solver = pyfluent.launch_fluent(precision='double', processor_count=2, mode='solver')
Shutting down Server...
pyfluent.launcher WARNING: PyFluent Watchdog did not initialize correctly, proceeding without it... 

```

The session continues to run until user tries to carry out further instructions, at which point the following message is given;

```
>>> solver.file.read(file_type="case", file_name = "pyfluent_meshing_examples/wing.msh.h5")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\session_solver.py", line 263, in __getattr__
self._populate_settings_api_root()
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\session_solver.py", line 260, in _populate_settings_api_root
self._settings_api_root = _import_settings_root(self._root)
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\session_solver.py", line 198, in _root
self._settings_root = flobject.get_root(
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1896, in get_root
obj_info = flproxy.get_static_info()
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\settings.py", line 112, in _fn
return fn(self, *args, **kwds)
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\settings.py", line 295, in get_static_info
response = self._service_impl.get_static_info(request)
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\settings.py", line 76, in get_static_info
return self.__stub.GetStaticInfo(request, metadata=self.__metadata)
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\grpc\_interceptor.py", line 216, in __call__
response, ignored_call = self._with_call(request,
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\grpc\_interceptor.py", line 254, in _with_call
call = self._interceptor.intercept_unary_unary(continuation,
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 122, in intercept_unary_unary
return self._intercept_call(continuation, client_call_details, request)
File "C:\ANSYSDev\ANSYS Inc\v242\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 112, in _intercept_call
raise ex from None
RuntimeError: failed to connect to all addresses; last error: UNAVAILABLE: WSA Error 

```

**Running the same scenario on a pyconsole session does not give any errors and user can successfully read case and use the session as normal**

### 📝 Steps to reproduce

1. on a shared network drive that the user does not have read/write access for, launch a standalone pyfluent session from the python executable in commonfiles;
```
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent(precision='double', processor_count=2, mode='solver')
```
2. see above `Shutting down Server` message in pyfluent session
3. continue by trying to read a file into session from the network drive
```
solver.file.read(file_type="case", file_name = "<>")
```
4. See above error generated
5. Repeat in same working directory but in a pyconsole session with new pyfluent integration enabled

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

v242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A - run from commonfiles python
```

**Comment by millerj97** [comment]
@cj-hodgson @seanpearsonuk @mkundu1

**Comment by seanpearsonuk** [comment]
The connection depends on Fluent writing the server info file.

**Comment by millerj97** [comment]
@seanpearsonuk can the user get a better error to tell them this?

**Comment by raph-luc** [comment]
We can check for write permissions before launching Fluent, abort the launch if no permissions, and provide a more helpful error message

**Comment by seanpearsonuk** [comment]
> @seanpearsonuk can the user get a better error to tell them this?

We actually want to do something better, but I was just putting the general information there...

**Comment by mkundu1** [comment]
@millerj97 Can you please check if this issue is fixed by setting the environment variable `SERVER_INFO_DIR` to path the user has permissions for?

We shall look into for a general fix for this issue.

**Comment by millerj97** [comment]
@mkundu1 This did not appear to work unfortunately

**Comment by seanpearsonuk** [comment]
@millerj97 Please can you run Fluent directly there and try to start the gRPC server from within Fluent itself?

**Comment by millerj97** [comment]
@seanpearsonuk this did work provided I write the server_info_file to a directory with correct permissions

**Comment by seanpearsonuk** [comment]
...but setting `SERVER_INFO_DIR` to that same path triggers the original error. Is the file ever written in that case?

**Comment by mkundu1** [comment]
@millerj97 Can you please share the log with `SERVER_INFO_DIR`? By executing `pyfluent.logging.enable()`, you can get the log in a pyfluent.log file in the working directory

**Comment by millerj97** [comment]
> ...but setting `SERVER_INFO_DIR` to that same path triggers the original error. Is the file ever written in that case?

@seanpearsonuk setting SERVER_INFO_DIR to a valid path and then launching `solver = pyfluent.launch_fluent()` created a server info file which appears for a few seconds and then is deleted


@mkundu1 setting the pyfluent.logging.enable() I get a permissions error for working directory, when SERVER_INFO_DIR is set to a valid directory but python is launched from a non-permitted directory - is this the workflow you intended?

**Comment by mkundu1** [comment]
@millerj97 Can you please try this?
```
import ansys.fluent.core as pyfluent
config_dict = pyfluent.logging.get_default_config()
config_dict['handlers']['pyfluent_file']['filename'] = <some filename.log in permitted directory>
pyfluent.logging.enable(custom_config=config_dict)
solver = pyfluent.launch_fluent()
```

**Comment by millerj97** [comment]
@mkundu1 that worked 
[pyfluent_log.log](https://github.com/ansys/pyfluent/files/14692471/pyfluent_log.log)

**Comment by vishalrat** [comment]
@millerj97 
I am trying to launch fluent from pyfluent on HPC
please help me by provinding your suggestions 

python code:-
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent()

I am getting following error:- 

pyfluent.launcher ERROR: Exception caught - TimeoutError: The launch process has timed out.
Traceback (most recent call last):
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/launcher/standalone_launcher.py", line 264, in __call__
    raise ex
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/launcher/standalone_launcher.py", line 248, in __call__
    _await_fluent_launch(
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/launcher/launcher_utils.py", line 72, in _await_fluent_launch
    raise TimeoutError("The launch process has timed out.")
TimeoutError: The launch process has timed out.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/launcher/launcher.py", line 302, in launch_fluent
    return launcher()
           ^^^^^^^^^^
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/launcher/standalone_launcher.py", line 305, in __call__
    raise LaunchFluentError(launch_cmd) from ex
ansys.fluent.core.launcher.error_handler.LaunchFluentError:
Fluent Launch string: nohup /ots/sw/ansys_inc/v232/fluent/bin/fluent 3ddp -gu -sifile=/tmp/tmpdir/ux815e/serverinfo-lukvu5pm.txt -nm &

**Comment by mkundu1** [comment]
@vishalrat Can you please enable logging and share pyfluent.log generated in the working directory?
```
import ansys.fluent.core as pyfluent
pyfluent.logging.enable()
solver = pyfluent.launch_fluent()
```

**Comment by vishalrat** [comment]
@mkundu1 @millerj97 

SHaring my pyfluent/log generated after using above mentioned:-


4 22:05:30,361 pyfluent.networking   DEBUG    Can use 127.0.0.1 as remoting ip
2024-07-14 22:05:30,366 pyfluent.launcher     DEBUG    Launching Fluent with command: nohup /ots/sw/ansys_inc/v232/fluent/bin/fluent 3ddp -gu -sifile=/tmp/tmpdir/ux815e/serverinfo-8jiqkzln.txt -nm &
2024-07-14 22:05:31,367 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:05:31,367 pyfluent.launcher     INFO     ...59 seconds remaining
2024-07-14 22:05:32,367 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:05:32,367 pyfluent.launcher     INFO     ...58 seconds remaining
2024-07-14 22:05:33,368 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:05:33,368 pyfluent.launcher     INFO     ...57 seconds remaining
2024-07-14 22:05:34,368 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:05:34,368 pyfluent.launcher     INFO     ...56 seconds remaining
2024-07-14 22:05:35,368 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:05:35,368 pyfluent.launcher     INFO     ...55 seconds remaining
2024-07-14 22:05:36,369 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:05:36,369 pyfluent.launcher     INFO     ...54 seconds remaining
2024-07-14 22:05:37,369 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:05:37,369 pyfluent.launcher     INFO     ...53 seconds remaining
2024-07-14 22:05:38,369 pyfluent.launcher     INFO     Waiting for Fluent to launch...
.
.
.

.2024-07-14 22:06:27,384 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:06:27,384 pyfluent.launcher     INFO     ...3 seconds remaining
2024-07-14 22:06:28,384 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:06:28,384 pyfluent.launcher     INFO     ...2 seconds remaining
2024-07-14 22:06:29,384 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:06:29,384 pyfluent.launcher     INFO     ...1 seconds remaining
2024-07-14 22:06:30,385 pyfluent.launcher     INFO     Waiting for Fluent to launch...
2024-07-14 22:06:30,385 pyfluent.launcher     INFO     ...0 seconds remaining
2024-07-14 22:06:30,385 pyfluent.launcher     ERROR    Exception caught - TimeoutError: The launch process has timed out.

**Comment by mkundu1** [comment]
The issue can be any of the following:

1. Fluent cannot locate the server info filepath (`/tmp/tmpdir/ux815e/serverinfo-8jiqkzln.txt`) provided by PyFluent.
2. PyFluent cannot connect to Fluent through the ip address written by Fluent in the server info file.

For 1, can you please check whether the parent path `/tmp/tmpdir/ux815e` is accessible and identical from the machines launching Fluent and PyFluent?

For 2, can you please launch Fluent separately and connect to Fluent from PyFluent? You can launch Fluent using the command: `/ots/sw/ansys_inc/v232/fluent/bin/fluent 3ddp -gu -sifile=<shared path>/server.txt -nm`. Then, in a separate terminal, execute the following PyFluent code:
```
import ansys.fluent.core as pyfluent
solver = pyfluent.connect_to_fluent(server_info_file_name="<shared path>/server.txt")
```

Issue 1 can be solved by setting the environment variable `SERVER_INFO_DIR` to a path common to both machines.

Issue 2 can be solved by setting the environment variable `REMOTING_SERVER_ADDRESS` to the correct ip address of the server.

**Comment by vishalrat** [comment]
@mkundu1 

"/tmp/tmpdir/ux815e" this path is accessible but  "serverinfo-8jiqkzln.txt" this file is not created.

I have tried running this command 
/ots/sw/ansys_inc/v232/fluent/bin/fluent 3ddp -gu -sifile=/ptmp/ux815e/ansys/server.txt -nm
which worked and then used the following code 

import ansys.fluent.core as pyfluent
solver = pyfluent.connect_to_fluent(server_info_file_name="/ptmp/ux815e/ansys/server.txt")

which gave me this error:-

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/launcher/launcher.py", line 357, in connect_to_fluent
    fluent_connection = FluentConnection(
                        ^^^^^^^^^^^^^^^^^
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/fluent_connection.py", line 305, in __init__
    self.health_check_service.check_health()
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/services/health_check.py", line 62, in check_health
    response = self._stub.Check(request, metadata=self._metadata)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/grpc/_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
                             ^^^^^^^^^^^^^^^^
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/grpc/_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/services/interceptors.py", line 122, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ptmp/nj787e/builds/python3/lib/python3.11/site-packages/ansys/fluent/core/services/interceptors.py", line 112, in _intercept_call
    raise ex from None
RuntimeError: failed to connect to all addresses; last error: UNKNOWN: ipv4:192.65.99.35:31060: HTTP proxy returned response code 502

---------------------------------------------------------------------------------------------------------------

After I have tried setting "SERVER_INFO_DIR" to /ptmp/ux815e/ansys on .bashrc script 
on restarting the terminal 
I got same error after using same code.

setting the "REMOTING_SERVER_ADDRESS" also give the same error

**Comment by vishalrat** [comment]
@mkundu1 

Any suggestion related tho above error, it will be very helpful

**Comment by mkundu1** [comment]
Looks like the client was able to read the ip/port 192.65.99.35:31060 from the server-info file, but failed during connection. So, the issue is correctly determining the server ip address the client can connect to. Are you able to ping the server machine via the ip address 192.65.99.35 from the client machine?

You can list all ip addresses in the server machine using the `ifconfig` command. One of them should be reachable from the client machine. We need to set `REMOTING_SERVER_ADDRESS` to that ip address.

**Comment by hpohekar** [comment]
> [@mkundu1](https://github.com/mkundu1) that worked [pyfluent_log.log](https://github.com/ansys/pyfluent/files/14692471/pyfluent_log.log)

The provided suggestion worked. Closing this now.

cc: @seanpearsonuk
