### ISSUE TITLE
"EventSubscription Object has no attribute status" in meshing

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#2616]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The following message is being displayed for a large number of commands in pyfluent standalone, however it does not appear to affect the output of the commands;

```
watertight=meshing.watertight()

Exception ignored in: <function EventSubscription.__del__ at 0x7f70f29a92d0>
Traceback (most recent call last):
  File "/v242/commonfiles/CPython/3_10/linx64/Release/python/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_se.py", line 373, in __del__
    self.unsubscribe()
  File "/v242/commonfiles/CPython/3_10/linx64/Release/python/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_se.py", line 362, in unsubscribe
    if self.status == DataModelProtoModule.STATUS_SUBSCRIBED:
AttributeError: 'EventSubscription' object has no attribute 'status'
Exception ignored in: <function EventSubscription.__del__ at 0x7f70f29a92d0>
Traceback (most recent call last):
  File "/v242/commonfiles/CPython/3_10/linx64/Release/python/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_se.py", line 373, in __del__
    self.unsubscribe()
  File "/v242/commonfiles/CPython/3_10/linx64/Release/python/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_se.py", line 362, in unsubscribe
    if self.status == DataModelProtoModule.STATUS_SUBSCRIBED:
AttributeError: 'EventSubscription' object has no attribute 'status'
Exception ignored in: <function EventSubscription.__del__ at 0x7f70f29a92d0>
Traceback (most recent call last):
  File "/v242/commonfiles/CPython/3_10/linx64/Release/python/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_se.py", line 373, in __del__
    self.unsubscribe()
  File "/v242/commonfiles/CPython/3_10/linx64/Release/python/lib/python3.10/site-packages/ansys/fluent/core/services/datamodel_se.py", line 362, in unsubscribe
    if self.status == DataModelProtoModule.STATUS_SUBSCRIBED:
AttributeError: 'EventSubscription' object has no attribute 'status'

```

### 📝 Steps to reproduce

 - launch python from common files
 
```
import ansys.fluent.core as pyfluent
from ansys.fluent.core import examples


wing_spaceclaim_file, wing_intermediary_file = [examples.download_file(CAD_file, "pyfluent/external_compressible") for CAD_file in ["wing.scdoc", "wing.pmdb"]]
print(wing_intermediary_file)

meshing = pyfluent.launch_fluent(precision='double', ui_mode='gui', processor_count=4, mode='meshing')

watertight=meshing.watertight()

```

occurs with and without GUI mode enabled

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

v242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A - commonfiles python
```

**Comment by millerj97** [comment]
@answillgm @cj-hodgson @seanpearsonuk @mkundu1

**Comment by prmukherj** [comment]
@millerj97, could you please specify the PyFluent version. This should have been fixed now.

**Comment by seanpearsonuk** [comment]
> @millerj97, could you please specify the PyFluent version. This should have been fixed now.

Yes, this was my opinion too.

**Comment by seanpearsonuk** [comment]
> > @millerj97, could you please specify the PyFluent version. This should have been fixed now.
> 
> Yes, this was my opinion too.

...perhaps not in a stable release version yet?

**Comment by prmukherj** [comment]
@millerj97, this ha already been fixed and released as 0.20.dev11. This was although a PyFluent issue, which was not affecting PyConsole anyway.

**Comment by millerj97** [comment]
@prmukherj ok great thanks, this is latest build we have available at the moment

**Comment by prmukherj** [comment]
@millerj97, this can be closed right?
