### ISSUE TITLE
Read-only preferences issue

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#2664]
Please make sure to delete \<HOME>/.fluentconf to reset the preferences before testing.
```
>>> import ansys.fluent.core as pyfluent
>>> solver = pyfluent.launch_fluent()
>>> m = solver.preferences.MeshingWorkflow
>>> m.SaveCheckpointFiles()
True
>>> m.CheckpointingOption.is_read_only()
True
>>> m.SaveCheckpointFiles = False
>>> m.SaveCheckpointFiles()
False
>>> m.CheckpointingOption.is_read_only()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 872, in is_read_only
    return false_if_none(self.get_attr(Attribute.IS_READ_ONLY.value))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 1214, in false_if_none      
    return _bool_value_if_none(val, default=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\datamodel_se.py", line 1204, in _bool_value_if_none
    raise TypeError(f"{val} should be a bool or None")
TypeError: <ansys.fluent.core.datamodel_242.preferences.Root.MeshingWorkflow.CheckpointingOption object at 0x0000021550E86450> should be a bool or None
```
I've added a test [test_read_only_preferences](https://github.com/ansys/pyfluent/blob/dcd8ad46406e90fe42129480e7bf5acce55da31c/tests/test_preferences.py#L86) in the branch test/read_only_preferences to demonstrate the issue.

Please see the corresponding Fluent defect for more details.

**Comment by seanpearsonuk** [comment]
@hpohekar Please could you follow up to complete the work here referenced in the PR. We can discussed.

**Comment by hpohekar** [comment]
> @hpohekar Please could you follow up to complete the work here referenced in the PR. We can discuss #2670.

@seanpearsonuk Yes, we will discuss this soon. Thank you.
