### ISSUE TITLE
Python 3.9.0 compatibility with PyFluent 0.20

### ISSUE THREAD

**Issue by mhoeijm** [ansys/pyfluent#2847]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I am getting a `TypeError: unhashable type: 'list'` when trying to import pyfluent in a clean Python 3.9.0 virtual environment (managed through conda): 

```
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:53:15) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ansys.fluent.core as pyfluent
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\ansys\fluent\core\__init__.py", line 19, in <module>
    from ansys.fluent.core.launcher.launcher import (  # noqa: F401
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 14, in <module>
    from ansys.fluent.core.launcher.container_launcher import DockerLauncher
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\ansys\fluent\core\launcher\container_launcher.py", line 21, in <module>
    from ansys.fluent.core.launcher.error_handler import _process_invalid_args
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\ansys\fluent\core\launcher\error_handler.py", line 4, in <module>
    from ansys.fluent.core.launcher import launcher_utils
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\ansys\fluent\core\launcher\launcher_utils.py", line 12, in <module>
    from beartype import BeartypeConf, beartype
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\beartype\__init__.py", line 58, in <module>
    from beartype._decor.decormain import (
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\beartype\_decor\decormain.py", line 23, in <module>
    from beartype._conf.confcls import (
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\beartype\_conf\confcls.py", line 46, in <module>
    from beartype._conf.confoverrides import (
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\beartype\_conf\confoverrides.py", line 15, in <module>
    from beartype._data.hint.datahinttyping import (
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\site-packages\beartype\_data\hint\datahinttyping.py", line 212, in <module>
    BeartypeReturn = Union[BeartypeableT, BeartypeConfedDecorator]
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\typing.py", line 243, in inner
    return func(*args, **kwds)
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "C:\ProgramData\miniforge3\envs\pyfluent-0.20-py39\lib\typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'
```

Upgrading to Python 3.10 seems to resolve the issue, and I do not get this `TypeError`. The docs suggest that Python 3.9 should still be supported though.

### 📝 Steps to reproduce

- Create Python 3.9.0 virtual environment through conda
- Install pyfluent 0.20
- try to import pyfluent

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

R24.1

### 🐍 Which Python version are you using?

3.9.0

### 📦 Installed packages

```shell
Python 3.9.0 environment: 

about-time==4.2.1
alive-progress==3.1.5
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.1.0
ansys-fluent-core==0.20.0
ansys-platform-instancemanagement==1.1.2
ansys-units==0.3.2
beartype==0.17.2
certifi==2024.2.2
charset-normalizer==3.3.2
docker==6.1.3
grapheme==0.6.0
grpcio==1.64.0
grpcio-health-checking==1.48.2
idna==3.7
importlib_metadata==7.1.0
lxml==4.9.4
numpy==1.26.4
packaging==24.0
pandas==1.5.3
platformdirs==3.11.0
protobuf==3.20.3
psutil==5.9.8
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
PyYAML==6.0.1
requests==2.32.1
six==1.16.0
urllib3==2.2.1
websocket-client==1.8.0
zipp==3.18.2

#######################

Python 3.10 environment:

about-time==4.2.1
alive-progress==3.1.5
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.1.0
ansys-fluent-core==0.20.0
ansys-platform-instancemanagement==1.1.2
ansys-units==0.3.2
beartype==0.17.2
certifi==2024.2.2
charset-normalizer==3.3.2
docker==6.1.3
grapheme==0.6.0
grpcio==1.64.0
grpcio-health-checking==1.48.2
idna==3.7
importlib_metadata==7.1.0
lxml==4.9.4
numpy==1.26.4
packaging==24.0
pandas==1.5.3
platformdirs==3.11.0
protobuf==3.20.3
psutil==5.9.8
python-dateutil==2.9.0.post0
pytz==2024.1
pywin32==306
PyYAML==6.0.1
requests==2.32.1
six==1.16.0
urllib3==2.2.1
websocket-client==1.8.0
zipp==3.18.2
```

**Comment by prmukherj** [comment]
Hi @mhoeijm,
![image](https://github.com/ansys/pyfluent/assets/109645853/9ff9ec1d-0e3e-4ddd-8699-0b992720ed1d)

I am not able to reproduce this issue using python 3.9.12
![image](https://github.com/ansys/pyfluent/assets/109645853/8765a41c-ac42-4f97-b254-86085f38cdeb)

Could you please try it once in a fresh environment and let us know.
Thank you

**Comment by mhoeijm** [comment]
The devil seems to be in the details: Pyfluent import fails with Python 3.9.0, but succeeds with 3.9.12 on my side.

**Comment by prmukherj** [comment]
@mhoeijm, the issue seems to be here:
![image](https://github.com/ansys/pyfluent/assets/109645853/b62bfe8f-5b0a-455c-9c41-97b6e9374607)

**Comment by sravanansys** [comment]
@hpohekar we need to update the documentation about the support for reliable python versions. Since 3.9-3.12 is mentioned as supported versions, we will have users using 3.9.0 and they will face issues.

**Comment by hpohekar** [comment]
@sravanansys Sure. Thank you.
