### ISSUE TITLE
semantic matching for failed calls

### ISSUE THREAD

**Issue by seanpearsonuk** [ansys/pyfluent#2884]
```
>>> solver.solution.run_calculation.solve()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\ANSYSDev\devZ3\vNNN\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1036, in __getattribute__
    attr = super().__getattribute__(name)
AttributeError: 'run_calculation' object has no attribute 'solve'.
The most similar names are: residual_verbosity.
```
Not the most helpful advice so we need to change the threshold. Also, this looks like a good opportunity to use semantic matching - that could produce some cool results.

**Comment by mkundu1** [comment]
Please also consider the issue #2218 while implementing this.
