### ISSUE TITLE
AttributeError: vmag is not an allowed Settings objects name. The most similar names are: thermal.

### ISSUE THREAD

**Issue by kangchouapp** [ansys/pyfluent#2938]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Traceback (most recent call last):
  File "D:\dingdan2024\CFD\pyCFDansys2024\pyCFDansys2024\AITF.py", line 107, in <module>
    solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].vmag = {
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 566, in __setattr__
    attr = getattr(self, name)
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 554, in __getattribute__
    return super().__getattribute__(name)
AttributeError: vmag is not an allowed Settings objects name.
The most similar names are: thermal.

### 📝 Steps to reproduce

Traceback (most recent call last):
  File "D:\dingdan2024\CFD\pyCFDansys2024\pyCFDansys2024\AITF.py", line 107, in <module>
    solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].vmag = {
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 566, in __setattr__
    attr = getattr(self, name)
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 554, in __getattribute__
    return super().__getattribute__(name)
AttributeError: vmag is not an allowed Settings objects name.
The most similar names are: thermal.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Traceback (most recent call last):
  File "D:\dingdan2024\CFD\pyCFDansys2024\pyCFDansys2024\AITF.py", line 107, in <module>
    solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].vmag = {
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 566, in __setattr__
    attr = getattr(self, name)
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 554, in __getattribute__
    return super().__getattribute__(name)
AttributeError: vmag is not an allowed Settings objects name.
The most similar names are: thermal.

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
Traceback (most recent call last):
  File "D:\dingdan2024\CFD\pyCFDansys2024\pyCFDansys2024\AITF.py", line 107, in <module>
    solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].vmag = {
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 566, in __setattr__
    attr = getattr(self, name)
  File "D:\anaconda3\envs\py39\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 554, in __getattribute__
    return super().__getattribute__(name)
AttributeError: vmag is not an allowed Settings objects name.
The most similar names are: thermal.
```

**Comment by mkundu1** [comment]
The path will be `solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].momentum.velocity.value` in later versions of PyFluent. Please see [this](https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/mixing_elbow_settings_api.html#set-up-boundary-conditions-for-cfd-analysis) tutorial script for settings up boundary conditions.

**Comment by kangchouapp** [comment]
> The path will be `solver.setup.boundary_conditions.velocity_inlet["cold-inlet"].momentum.velocity.value` in later versions of PyFluent. Please see [this](https://fluent.docs.pyansys.com/version/stable/examples/00-fluent/mixing_elbow_settings_api.html#set-up-boundary-conditions-for-cfd-analysis) tutorial script for settings up boundary conditions.


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 solver.setup.cell_zone_conditions.fluid["elbow-fluid"].general.material = "water-liquid"

File D:\anaconda3\envs\py39fluent\lib\site-packages\ansys\fluent\core\solver\flobject.py:554, in Group.__getattribute__(self, name)
    552         raise RuntimeError(f"'{self.path}' is currently not active")
    553 try:
--> 554     return super().__getattribute__(name)
    555 except AttributeError as ex:
    556     self._get_parent_of_active_child_names(name)

AttributeError: general is not an allowed Settings objects name.
The most similar names are: material.
