### ISSUE TITLE
Wildcard gives key error 

### ISSUE THREAD

**Issue by hpohekar** [ansys/pyfluent#3080]
@seanpearsonuk @mkundu1 

Following code gives KeyError - 

```
session.setup.boundary_conditions.wall['wall-geom*'] = {
    "thermal" : {
        "free_stream_temp" : 300,
        "heat_transfer_coeff" : 100,
        "thermal_condition" : "Convection"}
    }
```

```
Traceback (most recent call last):
  File "D:\Repos\pyfluent-examples\examples\00-released_examples\01-brake.py", line 136, in <module>
    session.setup.boundary_conditions.wall['wall-geom*'] = {
  File "D:\Repos\pyfluent-examples\venv\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1784, in __setitem__
    raise KeyError(name)
KeyError: 'wall-geom*'
```

Equivalent tui code is as follows - 

```
session.tui.define.boundary_conditions.set.wall(
    "wall-disc*",
    "wall-geom*",
    "()",
    "thermal-bc",
    "yes",
    "convection",
    "convective-heat-transfer-coefficient",
    "no",
    100,
    "q",
)
```

https://examples.fluent.docs.pyansys.com/version/dev/examples/00-released_examples/01-brake.html

**Comment by mkundu1** [comment]
There is a limitation in Fluent side to implement this, logged Fluent defect 1099706

**Comment by hpohekar** [comment]
> There is a limitation in Fluent side to implement this, logged Fluent defect 1099706

Thank you.
