### ISSUE TITLE
Odd intermittent scheme error when saving pictures

### ISSUE THREAD

**Issue by AdamTheEngineer-dev** [ansys/pyfluent#3147]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

I'm saving a lot of pictures using code of the form:

```
time_stamp = f"{time*1000}ms"
solver.results.graphics.picture.save_picture(file_name=f"b_flux_planes_{time_stamp}.png")
```
but every so often it causes a scheme error :
```
Error: wta(1st) to string->symbol
Error Object: #[free (3 cells)]
```

The full error is:

```
Error: wta(1st) to string->symbol
Error Object: #[free (3 cells)]
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\ALIP_3.89kg.s.-1\alip_utils.py", line 15, in save_plots
    fluent_runner.solver.results.graphics.picture.save_picture(file_name=f"b_flux_planes_{time_stamp}.png")
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1614, in __call__
    return self.execute_command(**kwds)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1575, in execute_command
    kwds[arg] = argument.after_execute(
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 404, in after_execute
    base_file_name = self._do_after_execute(
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 840, in _do_after_execute
    if self.file_transfer_service:
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 240, in file_transfer_service
    return self._parent.file_transfer_service
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 240, in file_transfer_service
    return self._parent.file_transfer_service
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1055, in __getattribute__
    attr = super().__getattribute__(name)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 239, in file_transfer_service
    elif self._parent:
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1743, in __len__
    cobj = getattr(self, cname)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1057, in __getattribute__
    attr._check_stable()
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 356, in _check_stable
    if not self.is_active():
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 351, in is_active
    attr = self.get_attr(_InlineConstants.is_active)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 328, in get_attr
    attrs = self.get_attrs([attr])
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 302, in get_attrs
    return self.flproxy.get_attrs(self.path, attrs, recursive)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\settings.py", line 124, in _fn
    return fn(self, *args, **kwds)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\settings.py", line 362, in get_attrs
    response = self._service_impl.get_attrs(request)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\settings.py", line 103, in get_attrs
    return self.__stub.GetAttrs(request, metadata=self.__metadata)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\grpc\_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 122, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 112, in _intercept_call
    raise ex from None
RuntimeError: wta(1st) to string->symbol
Error Object: #[free (3 cells)]


Then second call gives:

Error: Attempt to mark a free block
Error Object: #[free (3 cells)]
Error encountered in critical code section
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\ALIP_3.89kg.s.-1\alip_utils.py", line 23, in save_plots
    fluent_runner.solver.results.scene.display(object_name="vels")
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1614, in __call__
    return self.execute_command(**kwds)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1572, in execute_command
    ret = self._execute_command(*args, **kwds)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\solver\flobject.py", line 1609, in _execute_command
    return self.flproxy.execute_cmd(self._parent.path, self.obj_name, **newkwds)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\settings.py", line 124, in _fn
    return fn(self, *args, **kwds)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\settings.py", line 329, in execute_cmd
    response = self._service_impl.execute_cmd(request)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\settings.py", line 91, in execute_cmd
    return self.__stub.ExecuteCommand(request, metadata=self.__metadata)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\grpc\_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 122, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "D:\OneDrive_ANSYS\OneDrive - ANSYS, Inc\examples\MHD\Argonne_Generic_ALIP\.venv_Argonne_Generic_ALIP\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 112, in _intercept_call
    raise ex from None
RuntimeError: End of TCP stream
```

### 📝 Steps to reproduce

Somehow get a script to write thousands of pictures and see if it happens again...

I am however running this on a Linux cluster using Slurm and connecting from Windows

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2024R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
about-time==4.2.1
alive-progress==3.1.5
annotated-types==0.7.0
ansys-api-fluent==0.3.25
ansys-api-platform-instancemanagement==1.1.0
ansys-api-tools-filetransfer==0.1.0
ansys-fluent-core==0.21.0
ansys-platform-instancemanagement==1.1.2
ansys-pythonnet==3.1.0rc3
ansys-tools-filetransfer==0.1.0
ansys-units==0.3.2
attrs==23.2.0
bcrypt==4.1.3
beartype==0.18.5
certifi==2024.7.4
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
contourpy==1.2.1
cryptography==42.0.8
cycler==0.12.1
defusedxml==0.7.1
docker==6.1.3
fonttools==4.53.0
fpdf2==2.7.9
grapheme==0.6.0
grpcio==1.64.1
grpcio-health-checking==1.62.2
h5py==3.11.0
idna==3.7
importlib_metadata==8.0.0
joblib==1.4.2
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
kiwisolver==1.4.5
lxml==4.9.4
matplotlib==3.9.1
nltk==3.8.1
numpy==1.26.4
opencv-python==4.10.0.84
packaging==24.1
pandas==2.2.2
paramiko==3.4.0
pillow==10.4.0
platformdirs==3.11.0
plumbum==1.8.3
pooch==1.8.2
protobuf==4.25.3
psutil==5.9.8
pyaedt==0.9.9
pycparser==2.22
pydantic==2.7.4
pydantic_core==2.18.4
pyedb==0.21.0
PyNaCl==1.5.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.1
pyvista==0.44.0
pywin32==306
PyYAML==6.0.1
referencing==0.35.1
regex==2024.5.15
requests==2.31.0
rpds-py==0.18.1
rpyc==6.0.0
Rtree==1.2.0
SCons==4.7.0
scooby==0.10.0
six==1.16.0
toml==0.10.2
tqdm==4.66.4
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.2.2
vtk==9.3.1
websocket-client==1.8.0
zipp==3.19.2
```

**Comment by prmukherj** [comment]
@gyeole, Could you please have a look and let us know.
Thank you

@AdamTheEngineer-dev, are you facing this issue since you started using PyFluent to do this or was it an existing issue? 

cc. @seanpearsonuk

**Comment by AdamTheEngineer-dev** [comment]
There was a similar issue before, but that was meant to be fixed.
That was a memory leak I believe.

This looks like some scheme error.
It may be that something else caused an error and that the scheme layer gets hit first.

It may have nothing to do with PyFluent, but since it's intermittent, it's ahrd to check.
