### ISSUE TITLE
Output not helpful when no license is available

### ISSUE THREAD

**Issue by cj-hodgson** [ansys/pyfluent#3312]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When there isn't a Fluent license available, the PyFluent output is not helpful in letting the user know why Fluent has not been launched successfully.

```Python
>>> import ansys.fluent.core as pyfluent
>>> pyfluent.launch_fluent()
pyfluent.launcher ERROR: Exception caught - RuntimeError: IOCP/Socket: Connection reset (An existing connection was forcibly closed by the remote host.
 -- 10054)
Traceback (most recent call last):
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\launcher\standalone_launcher.py", line 259, in __call__
    session = self.new_session._create_from_server_info_file(
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\session.py", line 288, in _create_from_server_info_file
    fluent_connection = FluentConnection(
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\fluent_connection.py", line 385, in __init__
    self.health_check.check_health()
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\health_check.py", line 62, in check_health
    response = self._stub.Check(request, metadata=self._metadata)
  File "C:\ansysdev\PyAnsys\.pyansys_venv\lib\site-packages\grpc\_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File "C:\ansysdev\PyAnsys\.pyansys_venv\lib\site-packages\grpc\_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 122, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\services\interceptors.py", line 112, in _intercept_call
    raise ex from None
RuntimeError: IOCP/Socket: Connection reset (An existing connection was forcibly closed by the remote host.
 -- 10054)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\utils\deprecate.py", line 49, in wrapper
    return func(*args, **kwargs)
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\utils\deprecate.py", line 49, in wrapper
    return func(*args, **kwargs)
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\launcher\launcher.py", line 294, in launch_fluent
    return launcher()
  File "C:\ansysdev\ansys_inc\v251\commonfiles\CPython\3_10\winx64\Release\python\lib\site-packages\ansys\fluent\core\launcher\standalone_launcher.py", line 300, in __call__
    raise LaunchFluentError(self._launch_cmd) from ex
ansys.fluent.core.launcher.error_handler.LaunchFluentError:
Fluent Launch string: start "" C:\ansysdev\ansys_inc\v251\fluent\ntbin\win64\fluent.exe 3ddp -hidden -sifile=C:\Users\cjhodgso\AppData\Local\Temp\serverinfo-kxbw4o1t.txt -nm
>>>
```

### 📝 Steps to reproduce

Disable licensing and then call pyfluent.launch_fluent()

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

2025R1

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
2to3==1.0
about-time==4.2.1
absl-py==2.1.0
alive-progress==3.1.5
ansys-api-fluent==0.3.27
ansys-api-platform-instancemanagement==1.1.0
ansys-api-tools-filetransfer==0.1.0
ansys-fluent-core==0.26.0
ansys-fluent-visualization==0.14.0
ansys-fluidprops==25.1.3
ansys-hpcservices-file-management-v1==23.1.2407.30
ansys-hpcservices-file-transfer-v1==23.1.2407.30
ansys-hpcservices-global-permission-v1==23.1.2407.30
ansys-hpcservices-hardware-configuration-clusters-v1==23.1.2407.30
ansys-hpcservices-hardware-configuration-endpoints-v1==23.1.2407.30
ansys-hpcservices-hardware-configuration-queues-v1==23.1.2407.30
ansys-hpcservices-hardware-configuration-storages-v1==23.1.2407.30
ansys-hpcservices-job-management-jobs-v1==23.1.2407.30
ansys-hpcservices-job-management-logs-v1==23.1.2407.30
ansys-hpcservices-job-management-templates-v1==23.1.2407.30
ansys-hpcservices-service-management-v1==23.1.2407.30
ansys-hpcservices-user-management-v1==23.1.2407.30
ansys-platform-instancemanagement==1.1.2
ansys-pythonnet==3.1.0rc0
ansys-tools-filetransfer==0.1.0
ansys-units==0.3.2
anyio==4.6.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
astunparse==1.6.3
async-lru==2.0.4
attrs==24.2.0
babel==2.16.0
bcrypt==4.2.0
beartype==0.18.5
beautifulsoup4==4.12.3
black==24.8.0
bleach==6.1.0
blinker==1.8.2
certifi==2023.11.17
cffi==1.17.1
cfgv==3.4.0
charset-normalizer==3.3.2
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
comm==0.2.2
contourpy==1.3.0
cryptography==43.0.1
cycler==0.12.1
dash==2.18.1
dash-bootstrap-components==1.6.0
dash-core-components==2.0.0
dash-html-components==2.0.0
dash-table==5.0.0
debugpy==1.8.5
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.8
distro==1.9.0
docker==7.1.0
et-xmlfile==1.1.0
exceptiongroup==1.2.2
execnet==2.1.1
executing==2.1.0
fastjsonschema==2.20.0
filelock==3.16.1
Flask==3.0.3
flatbuffers==24.3.25
fonttools==4.53.1
fqdn==1.5.1
future==0.18.0
gast==0.6.0
google-pasta==0.2.0
googleapis-common-protos==1.52.0
grapheme==0.6.0
grpcio==1.66.1
grpcio-health-checking==1.48.1
grpcio-status==1.26.0
h11==0.14.0
h5py==3.11.0
httpcore==1.0.5
httpx==0.27.2
identify==2.6.1
idna==3.10
imageio==2.35.1
importlib_metadata==8.5.0
iniconfig==2.0.0
ipykernel==6.29.5
ipython==8.27.0
isoduration==20.11.0
itsdangerous==2.2.0
jedi==0.19.1
Jinja2==3.1.4
joblib==1.4.2
json5==0.9.25
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.14.2
jupyter_server_terminals==0.5.3
jupyterlab==4.2.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
kaleido==0.2.1
keras==3.5.0
kiwisolver==1.4.7
libclang==18.1.1
llvmlite==0.39.1
lxml==5.3.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.2
matplotlib-inline==0.1.7
mdurl==0.1.2
mistune==3.0.2
ml-dtypes==0.4.1
mypy-extensions==1.0.0
namex==0.0.8
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
nltk==3.9.1
nodeenv==1.9.1
notebook==7.2.2
notebook_shim==0.2.4
numba==0.56.4
numpy==1.23.5
openpyxl==3.1.5
opt-einsum==3.3.0
optree==0.12.1
overrides==7.7.0
packaging==24.1
pandas==2.0.3
pandocfilters==1.5.1
paramiko==3.5.0
paramiko-expect==0.3.5
parso==0.8.4
pathspec==0.12.1
pillow==10.4.0
pip-system-certs==4.0
platformdirs==4.3.3
plotly==5.24.1
pluggy==1.5.0
pooch==1.8.2
pre-commit==3.8.0
prometheus_client==0.21.0
prompt_toolkit==3.0.47
protobuf==4.25.4
psutil==6.0.0
pure_eval==0.2.3
py==1.11.0
pybind11==2.10.0
pycparser==2.22
Pygments==2.18.0
Pymem==1.13.1
PyNaCl==1.5.0
pyparsing==3.1.4
PySide6==6.7.2
PySide6_Addons==6.7.2
PySide6_Essentials==6.7.2
pytest==7.2.1
pytest-forked==1.6.0
pytest-xdist==1.31.0
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
python-pptx==1.0.2
pytz==2024.2
pyvista==0.44.1
pyvistaqt==0.11.1
pywin32==304
pywinpty==2.0.13
PyYAML==6.0.2
pyzmq==26.2.0
QtPy==2.4.1
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
retrying==1.3.4
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.8.1
rpds-py==0.20.0
scikit-learn==1.5.2
scipy==1.9.3
SCons==4.3.0
scooby==0.10.0
seaborn==0.13.2
Send2Trash==1.8.3
shapely==2.0.2
shiboken6==6.7.2
sip==6.5.1
six==1.16.0
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
tenacity==9.0.0
tensorboard==2.17.1
tensorboard-data-server==0.7.2
tensorflow==2.17.0
tensorflow-intel==2.17.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.4.0
terminado==0.18.1
threadpoolctl==3.5.0
tinycss2==1.3.0
toml==0.10.2
tomli==2.0.1
tornado==6.4.1
tqdm==4.66.5
traitlets==5.14.3
types-python-dateutil==2.9.0.20240906
typing_extensions==4.12.2
tzdata==2024.1
uri-template==1.3.0
urllib3==1.26.10
virtualenv==20.26.5
vtk==9.3.1
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
Werkzeug==3.0.4
wrapt==1.16.0
wxPython==4.2.0
xgboost==2.1.1
XlsxWriter==3.2.0
zipp==3.20.2
```

**Comment by hpohekar** [comment]
[T1141006].
