### ISSUE TITLE
Codegen should not fail when network is unavailable

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#3384]
Replicating the recent Fluent build error by running codegen by turning off internet:
```
D:\ANSYSDev\PyFluentDev\pyfluent>python codegen\allapigen.py
Time to fetch static info: 309.36 seconds
Generating builtin settings...
Time to generate APIs: 6.83 seconds
[nltk_data] Error loading wordnet: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
Traceback (most recent call last):
  File "D:\ANSYSDev\PyFluentDev\pyfluent\codegen\allapigen.py", line 69, in <module>
    _search("", version=version, write_api_tree_data=True)
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\search.py", line 293, in _search
    _write_api_tree_file(
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\search.py", line 268, in _write_api_tree_file
    _download_nltk_data()
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\search.py", line 537, in _download_nltk_data
    nltk.download(
  File "C:\Python312\Lib\site-packages\nltk\downloader.py", line 779, in download
    raise ValueError(msg.message)
ValueError: Error loading wordnet: <urlopen error [Errno 11001] getaddrinfo failed>
```
We should just log the above error and proceed. `nltk.download` has several options to control that behaviour. At runtime, we should safely handle the scenario when nltk data is unavailable or not downloadable.

Note that we can run Fluent using a local license server when the internet is off, so pyfluent should not be affected when the network is not available.

**Comment by mkundu1** [comment]
Additionally, we can consider packaging the nltk data separately within Fluent's commonfiles.

**Comment by hpohekar** [comment]
> Additionally, we can consider packaging the nltk data separately within Fluent's commonfiles.

@mkundu1 Yes, this is fine as well.
