### ISSUE TITLE
get_fields_info and get_scalar_fields_info call over the same rpc

### ISSUE THREAD

**Issue by mkundu1** [ansys/pyfluent#3590]
def get_fields_info(self, request):
        """GetFieldsInfo RPC of FieldData service."""
        return self._stub.GetFieldsInfo(request, metadata=self._metadata)

    def get_scalar_fields_info(self, request):
        """GetFieldsInfo RPC of FieldData service."""
        return self._stub.GetFieldsInfo(request, metadata=self._metadata)

We should have a single method to get the field info.

**Comment by mkundu1** [comment]
`get_fields_info` doesn't even work:
```
>>> field_info.get_fields_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\field_data.py", line 128, in get_fields_info
    request = FieldDataProtoModule.GetFieldsInfo()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ansys.api.fluent.v0.field_data_pb2' has no attribute 'GetFieldsInfo'. Did you mean: 'FieldInfo'?
```

**Comment by mkundu1** [comment]
The stable user guide and cheatsheet mentions `get_fields_info` which doesn't exist in the stable released version (0.27).

**Comment by hpohekar** [comment]
@mkundu1 

The docs should be updated.

![Image](https://github.com/user-attachments/assets/c15b8cfa-ddfd-4eeb-a88f-72c4000dbc7f)

https://github.com/ansys/pyfluent/issues/3603

**Comment by hpohekar** [comment]
> `get_fields_info` doesn't even work:
> 
> ```
> >>> field_info.get_fields_info()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "D:\ANSYSDev\PyFluentDev\pyfluent\src\ansys\fluent\core\services\field_data.py", line 128, in get_fields_info
>     request = FieldDataProtoModule.GetFieldsInfo()
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'ansys.api.fluent.v0.field_data_pb2' has no attribute 'GetFieldsInfo'. Did you mean: 'FieldInfo'?
> ```

Right, this should be `FieldDataProtoModule.GetFieldsInfo()`.
